/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_AuthenticateServerRequest_H_
#define	_AuthenticateServerRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ServerSigned1.h"
#include "OCTET_STRING.h"
#include "SubjectKeyIdentifier.h"
#include "Certificate.h"
#include "CtxParams1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AuthenticateServerRequest */
typedef struct AuthenticateServerRequest {
	ServerSigned1_t	 serverSigned1;
	OCTET_STRING_t	 serverSignature1;
	SubjectKeyIdentifier_t	 euiccCiPKIdToBeUsed;
	Certificate_t	 serverCertificate;
	CtxParams1_t	 ctxParams1;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AuthenticateServerRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuthenticateServerRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _AuthenticateServerRequest_H_ */
#include "asn_internal.h"
