/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "AuthenticateResponseOk.h"

asn_TYPE_member_t asn_MBR_AuthenticateResponseOk_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateResponseOk, euiccSigned1),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EuiccSigned1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccSigned1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateResponseOk, euiccSignature1),
		(ASN_TAG_CLASS_APPLICATION | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccSignature1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateResponseOk, euiccCertificate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Certificate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccCertificate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateResponseOk, eumCertificate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Certificate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eumCertificate"
		},
};
static const ber_tlv_tag_t asn_DEF_AuthenticateResponseOk_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AuthenticateResponseOk_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 2 }, /* euiccSigned1 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 1 }, /* euiccCertificate */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -2, 0 }, /* eumCertificate */
    { (ASN_TAG_CLASS_APPLICATION | (55 << 2)), 1, 0, 0 } /* euiccSignature1 */
};
asn_SEQUENCE_specifics_t asn_SPC_AuthenticateResponseOk_specs_1 = {
	sizeof(struct AuthenticateResponseOk),
	offsetof(struct AuthenticateResponseOk, _asn_ctx),
	asn_MAP_AuthenticateResponseOk_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AuthenticateResponseOk = {
	"AuthenticateResponseOk",
	"AuthenticateResponseOk",
	&asn_OP_SEQUENCE,
	asn_DEF_AuthenticateResponseOk_tags_1,
	sizeof(asn_DEF_AuthenticateResponseOk_tags_1)
		/sizeof(asn_DEF_AuthenticateResponseOk_tags_1[0]), /* 1 */
	asn_DEF_AuthenticateResponseOk_tags_1,	/* Same as above */
	sizeof(asn_DEF_AuthenticateResponseOk_tags_1)
		/sizeof(asn_DEF_AuthenticateResponseOk_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AuthenticateResponseOk_1,
	4,	/* Elements count */
	&asn_SPC_AuthenticateResponseOk_specs_1	/* Additional specs */
};

