/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_AuthenticateClientResponseEs9_H_
#define	_AuthenticateClientResponseEs9_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AuthenticateClientOk.h"
#include "INTEGER.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AuthenticateClientResponseEs9_PR {
	AuthenticateClientResponseEs9_PR_NOTHING,	/* No components present */
	AuthenticateClientResponseEs9_PR_authenticateClientOk,
	AuthenticateClientResponseEs9_PR_authenticateClientError
	/* Extensions may appear below */
	
} AuthenticateClientResponseEs9_PR;
typedef enum AuthenticateClientResponseEs9__authenticateClientError {
	AuthenticateClientResponseEs9__authenticateClientError_eumCertificateInvalid	= 1,
	AuthenticateClientResponseEs9__authenticateClientError_eumCertificateExpired	= 2,
	AuthenticateClientResponseEs9__authenticateClientError_euiccCertificateInvalid	= 3,
	AuthenticateClientResponseEs9__authenticateClientError_euiccCertificateExpired	= 4,
	AuthenticateClientResponseEs9__authenticateClientError_euiccSignatureInvalid	= 5,
	AuthenticateClientResponseEs9__authenticateClientError_matchingIdRefused	= 6,
	AuthenticateClientResponseEs9__authenticateClientError_eidMismatch	= 7,
	AuthenticateClientResponseEs9__authenticateClientError_noEligibleProfile	= 8,
	AuthenticateClientResponseEs9__authenticateClientError_ciPKUnknown	= 9,
	AuthenticateClientResponseEs9__authenticateClientError_invalidTransactionId	= 10,
	AuthenticateClientResponseEs9__authenticateClientError_undefinedError	= 127
} e_AuthenticateClientResponseEs9__authenticateClientError;

/* AuthenticateClientResponseEs9 */
typedef struct AuthenticateClientResponseEs9 {
	AuthenticateClientResponseEs9_PR present;
	union AuthenticateClientResponseEs9_u {
		AuthenticateClientOk_t	 authenticateClientOk;
		INTEGER_t	 authenticateClientError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AuthenticateClientResponseEs9_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuthenticateClientResponseEs9;
extern asn_CHOICE_specifics_t asn_SPC_AuthenticateClientResponseEs9_specs_1;
extern asn_TYPE_member_t asn_MBR_AuthenticateClientResponseEs9_1[2];
extern asn_per_constraints_t asn_PER_type_AuthenticateClientResponseEs9_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _AuthenticateClientResponseEs9_H_ */
#include "asn_internal.h"
