/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_AuthenticateClientOk_H_
#define	_AuthenticateClientOk_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TransactionId.h"
#include "StoreMetadataRequest.h"
#include "PrepareDownloadRequest.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AuthenticateClientOk */
typedef struct AuthenticateClientOk {
	TransactionId_t	 transactionId;
	StoreMetadataRequest_t	 profileMetaData;
	PrepareDownloadRequest_t	 prepareDownloadRequest;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AuthenticateClientOk_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuthenticateClientOk;
extern asn_SEQUENCE_specifics_t asn_SPC_AuthenticateClientOk_specs_1;
extern asn_TYPE_member_t asn_MBR_AuthenticateClientOk_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _AuthenticateClientOk_H_ */
#include "asn_internal.h"
