/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "AuthenticateClientOkEs11.h"

static asn_TYPE_member_t asn_MBR_eventEntries_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EventEntries,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_eventEntries_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_eventEntries_specs_3 = {
	sizeof(struct AuthenticateClientOkEs11__eventEntries),
	offsetof(struct AuthenticateClientOkEs11__eventEntries, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventEntries_3 = {
	"eventEntries",
	"eventEntries",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_eventEntries_tags_3,
	sizeof(asn_DEF_eventEntries_tags_3)
		/sizeof(asn_DEF_eventEntries_tags_3[0]) - 1, /* 1 */
	asn_DEF_eventEntries_tags_3,	/* Same as above */
	sizeof(asn_DEF_eventEntries_tags_3)
		/sizeof(asn_DEF_eventEntries_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_eventEntries_3,
	1,	/* Single element */
	&asn_SPC_eventEntries_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_AuthenticateClientOkEs11_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateClientOkEs11, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateClientOkEs11, eventEntries),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_eventEntries_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventEntries"
		},
};
static const ber_tlv_tag_t asn_DEF_AuthenticateClientOkEs11_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AuthenticateClientOkEs11_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* transactionId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* eventEntries */
};
asn_SEQUENCE_specifics_t asn_SPC_AuthenticateClientOkEs11_specs_1 = {
	sizeof(struct AuthenticateClientOkEs11),
	offsetof(struct AuthenticateClientOkEs11, _asn_ctx),
	asn_MAP_AuthenticateClientOkEs11_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AuthenticateClientOkEs11 = {
	"AuthenticateClientOkEs11",
	"AuthenticateClientOkEs11",
	&asn_OP_SEQUENCE,
	asn_DEF_AuthenticateClientOkEs11_tags_1,
	sizeof(asn_DEF_AuthenticateClientOkEs11_tags_1)
		/sizeof(asn_DEF_AuthenticateClientOkEs11_tags_1[0]), /* 1 */
	asn_DEF_AuthenticateClientOkEs11_tags_1,	/* Same as above */
	sizeof(asn_DEF_AuthenticateClientOkEs11_tags_1)
		/sizeof(asn_DEF_AuthenticateClientOkEs11_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AuthenticateClientOkEs11_1,
	2,	/* Elements count */
	&asn_SPC_AuthenticateClientOkEs11_specs_1	/* Additional specs */
};

