/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_AuthenticateClientResponseEs11_H_
#define	_AuthenticateClientResponseEs11_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AuthenticateClientOkEs11.h"
#include "INTEGER.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AuthenticateClientResponseEs11_PR {
	AuthenticateClientResponseEs11_PR_NOTHING,	/* No components present */
	AuthenticateClientResponseEs11_PR_authenticateClientOk,
	AuthenticateClientResponseEs11_PR_authenticateClientError
	/* Extensions may appear below */
	
} AuthenticateClientResponseEs11_PR;
typedef enum AuthenticateClientResponseEs11__authenticateClientError {
	AuthenticateClientResponseEs11__authenticateClientError_eumCertificateInvalid	= 1,
	AuthenticateClientResponseEs11__authenticateClientError_eumCertificateExpired	= 2,
	AuthenticateClientResponseEs11__authenticateClientError_euiccCertificateInvalid	= 3,
	AuthenticateClientResponseEs11__authenticateClientError_euiccCertificateExpired	= 4,
	AuthenticateClientResponseEs11__authenticateClientError_euiccSignatureInvalid	= 5,
	AuthenticateClientResponseEs11__authenticateClientError_eventIdUnknown	= 6,
	AuthenticateClientResponseEs11__authenticateClientError_invalidTransactionId	= 7,
	AuthenticateClientResponseEs11__authenticateClientError_undefinedError	= 127
} e_AuthenticateClientResponseEs11__authenticateClientError;

/* AuthenticateClientResponseEs11 */
typedef struct AuthenticateClientResponseEs11 {
	AuthenticateClientResponseEs11_PR present;
	union AuthenticateClientResponseEs11_u {
		AuthenticateClientOkEs11_t	 authenticateClientOk;
		INTEGER_t	 authenticateClientError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AuthenticateClientResponseEs11_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuthenticateClientResponseEs11;
extern asn_CHOICE_specifics_t asn_SPC_AuthenticateClientResponseEs11_specs_1;
extern asn_TYPE_member_t asn_MBR_AuthenticateClientResponseEs11_1[2];
extern asn_per_constraints_t asn_PER_type_AuthenticateClientResponseEs11_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _AuthenticateClientResponseEs11_H_ */
#include "asn_internal.h"
