/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "AuthenticateServerRequest.h"

static asn_TYPE_member_t asn_MBR_AuthenticateServerRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateServerRequest, serverSigned1),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ServerSigned1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serverSigned1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateServerRequest, serverSignature1),
		(ASN_TAG_CLASS_APPLICATION | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serverSignature1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateServerRequest, euiccCiPKIdToBeUsed),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_SubjectKeyIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccCiPKIdToBeUsed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateServerRequest, serverCertificate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Certificate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serverCertificate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateServerRequest, ctxParams1),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_CtxParams1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ctxParams1"
		},
};
static const ber_tlv_tag_t asn_DEF_AuthenticateServerRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (56 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AuthenticateServerRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 0 }, /* euiccCiPKIdToBeUsed */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* serverSigned1 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -1, 0 }, /* serverCertificate */
    { (ASN_TAG_CLASS_APPLICATION | (55 << 2)), 1, 0, 0 }, /* serverSignature1 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 4, 0, 0 } /* ctxParamsForCommonAuthentication */
};
static asn_SEQUENCE_specifics_t asn_SPC_AuthenticateServerRequest_specs_1 = {
	sizeof(struct AuthenticateServerRequest),
	offsetof(struct AuthenticateServerRequest, _asn_ctx),
	asn_MAP_AuthenticateServerRequest_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AuthenticateServerRequest = {
	"AuthenticateServerRequest",
	"AuthenticateServerRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_AuthenticateServerRequest_tags_1,
	sizeof(asn_DEF_AuthenticateServerRequest_tags_1)
		/sizeof(asn_DEF_AuthenticateServerRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_AuthenticateServerRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_AuthenticateServerRequest_tags_1)
		/sizeof(asn_DEF_AuthenticateServerRequest_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AuthenticateServerRequest_1,
	5,	/* Elements count */
	&asn_SPC_AuthenticateServerRequest_specs_1	/* Additional specs */
};

