/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "BoundProfilePackage.h"

asn_TYPE_member_t asn_MBR_BoundProfilePackage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BoundProfilePackage, initialiseSecureChannelRequest),
		(ASN_TAG_CLASS_CONTEXT | (35 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitialiseSecureChannelRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initialiseSecureChannelRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BoundProfilePackage, firstSequenceOf87),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_SeqBoundProfilePackageTLV87,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"firstSequenceOf87"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BoundProfilePackage, sequenceOf88),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_SeqBoundProfilePackageTLV88,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sequenceOf88"
		},
	{ ATF_POINTER, 1, offsetof(struct BoundProfilePackage, secondSequenceOf87),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_SeqSecondBoundProfilePackageTLV87,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"secondSequenceOf87"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BoundProfilePackage, sequenceOf86),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_SeqBoundProfilePackageTLV86,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sequenceOf86"
		},
};
static const int asn_MAP_BoundProfilePackage_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_BoundProfilePackage_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (54 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BoundProfilePackage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* firstSequenceOf87 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* sequenceOf88 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 }, /* secondSequenceOf87 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 4, 0, 0 }, /* sequenceOf86 */
    { (ASN_TAG_CLASS_CONTEXT | (35 << 2)), 0, 0, 0 } /* initialiseSecureChannelRequest */
};
asn_SEQUENCE_specifics_t asn_SPC_BoundProfilePackage_specs_1 = {
	sizeof(struct BoundProfilePackage),
	offsetof(struct BoundProfilePackage, _asn_ctx),
	asn_MAP_BoundProfilePackage_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_BoundProfilePackage_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_BoundProfilePackage = {
	"BoundProfilePackage",
	"BoundProfilePackage",
	&asn_OP_SEQUENCE,
	asn_DEF_BoundProfilePackage_tags_1,
	sizeof(asn_DEF_BoundProfilePackage_tags_1)
		/sizeof(asn_DEF_BoundProfilePackage_tags_1[0]) - 1, /* 1 */
	asn_DEF_BoundProfilePackage_tags_1,	/* Same as above */
	sizeof(asn_DEF_BoundProfilePackage_tags_1)
		/sizeof(asn_DEF_BoundProfilePackage_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_BoundProfilePackage_1,
	5,	/* Elements count */
	&asn_SPC_BoundProfilePackage_specs_1	/* Additional specs */
};

