/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_BoundProfilePackage_H_
#define	_BoundProfilePackage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "InitialiseSecureChannelRequest.h"
#include "SeqBoundProfilePackageTLV87.h"
#include "SeqBoundProfilePackageTLV88.h"
#include "SeqBoundProfilePackageTLV86.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SeqSecondBoundProfilePackageTLV87;

/* BoundProfilePackage */
typedef struct BoundProfilePackage {
	InitialiseSecureChannelRequest_t	 initialiseSecureChannelRequest;
	SeqBoundProfilePackageTLV87_t	 firstSequenceOf87;
	SeqBoundProfilePackageTLV88_t	 sequenceOf88;
	struct SeqSecondBoundProfilePackageTLV87	*secondSequenceOf87	/* OPTIONAL */;
	SeqBoundProfilePackageTLV86_t	 sequenceOf86;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BoundProfilePackage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BoundProfilePackage;
extern asn_SEQUENCE_specifics_t asn_SPC_BoundProfilePackage_specs_1;
extern asn_TYPE_member_t asn_MBR_BoundProfilePackage_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SeqSecondBoundProfilePackageTLV87.h"

#endif	/* _BoundProfilePackage_H_ */
#include "asn_internal.h"
