/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "CancelSessionResponseEs9.h"

static asn_oer_constraints_t asn_OER_type_CancelSessionResponseEs9_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_CancelSessionResponseEs9_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_CancelSessionResponseEs9_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CancelSessionResponseEs9, choice.cancelSessionOk),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CancelSessionOk,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cancelSessionOk"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CancelSessionResponseEs9, choice.cancelSessionError),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cancelSessionError"
		},
};
static const ber_tlv_tag_t asn_DEF_CancelSessionResponseEs9_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (65 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CancelSessionResponseEs9_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cancelSessionOk */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cancelSessionError */
};
asn_CHOICE_specifics_t asn_SPC_CancelSessionResponseEs9_specs_1 = {
	sizeof(struct CancelSessionResponseEs9),
	offsetof(struct CancelSessionResponseEs9, _asn_ctx),
	offsetof(struct CancelSessionResponseEs9, present),
	sizeof(((struct CancelSessionResponseEs9 *)0)->present),
	asn_MAP_CancelSessionResponseEs9_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CancelSessionResponseEs9 = {
	"CancelSessionResponseEs9",
	"CancelSessionResponseEs9",
	&asn_OP_CHOICE,
	asn_DEF_CancelSessionResponseEs9_tags_1,
	sizeof(asn_DEF_CancelSessionResponseEs9_tags_1)
		/sizeof(asn_DEF_CancelSessionResponseEs9_tags_1[0]), /* 1 */
	asn_DEF_CancelSessionResponseEs9_tags_1,	/* Same as above */
	sizeof(asn_DEF_CancelSessionResponseEs9_tags_1)
		/sizeof(asn_DEF_CancelSessionResponseEs9_tags_1[0]), /* 1 */
	{ &asn_OER_type_CancelSessionResponseEs9_constr_1, &asn_PER_type_CancelSessionResponseEs9_constr_1, CHOICE_constraint },
	asn_MBR_CancelSessionResponseEs9_1,
	2,	/* Elements count */
	&asn_SPC_CancelSessionResponseEs9_specs_1	/* Additional specs */
};

