/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_CancelSessionResponseEs9_H_
#define	_CancelSessionResponseEs9_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CancelSessionOk.h"
#include "INTEGER.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CancelSessionResponseEs9_PR {
	CancelSessionResponseEs9_PR_NOTHING,	/* No components present */
	CancelSessionResponseEs9_PR_cancelSessionOk,
	CancelSessionResponseEs9_PR_cancelSessionError
	/* Extensions may appear below */
	
} CancelSessionResponseEs9_PR;
typedef enum CancelSessionResponseEs9__cancelSessionError {
	CancelSessionResponseEs9__cancelSessionError_invalidTransactionId	= 1,
	CancelSessionResponseEs9__cancelSessionError_euiccSignatureInvalid	= 2,
	CancelSessionResponseEs9__cancelSessionError_undefinedError	= 127
} e_CancelSessionResponseEs9__cancelSessionError;

/* CancelSessionResponseEs9 */
typedef struct CancelSessionResponseEs9 {
	CancelSessionResponseEs9_PR present;
	union CancelSessionResponseEs9_u {
		CancelSessionOk_t	 cancelSessionOk;
		INTEGER_t	 cancelSessionError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CancelSessionResponseEs9_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CancelSessionResponseEs9;
extern asn_CHOICE_specifics_t asn_SPC_CancelSessionResponseEs9_specs_1;
extern asn_TYPE_member_t asn_MBR_CancelSessionResponseEs9_1[2];
extern asn_per_constraints_t asn_PER_type_CancelSessionResponseEs9_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CancelSessionResponseEs9_H_ */
#include "asn_internal.h"
