/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_CertificateInfo_H_
#define	_CertificateInfo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CertificateInfo {
	CertificateInfo_reserved	= 0,
	CertificateInfo_certSigningX509	= 1,
	CertificateInfo_rfu2	= 2,
	CertificateInfo_rfu3	= 3,
	CertificateInfo_reserved2	= 4,
	CertificateInfo_certVerificationX509	= 5
} e_CertificateInfo;

/* CertificateInfo */
typedef BIT_STRING_t	 CertificateInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateInfo;
asn_struct_free_f CertificateInfo_free;
asn_struct_print_f CertificateInfo_print;
asn_constr_check_f CertificateInfo_constraint;
ber_type_decoder_f CertificateInfo_decode_ber;
der_type_encoder_f CertificateInfo_encode_der;
xer_type_decoder_f CertificateInfo_decode_xer;
xer_type_encoder_f CertificateInfo_encode_xer;
oer_type_decoder_f CertificateInfo_decode_oer;
oer_type_encoder_f CertificateInfo_encode_oer;
per_type_decoder_f CertificateInfo_decode_uper;
per_type_encoder_f CertificateInfo_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CertificateInfo_H_ */
#include "asn_internal.h"
