/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ControlRefTemplate_H_
#define	_ControlRefTemplate_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Octet1.h"
#include "OctetTo16.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ControlRefTemplate */
typedef struct ControlRefTemplate {
	Octet1_t	 keyType;
	Octet1_t	 keyLen;
	OctetTo16_t	 hostId;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ControlRefTemplate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ControlRefTemplate;
extern asn_SEQUENCE_specifics_t asn_SPC_ControlRefTemplate_specs_1;
extern asn_TYPE_member_t asn_MBR_ControlRefTemplate_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ControlRefTemplate_H_ */
#include "asn_internal.h"
