/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_DeleteProfileRequest_H_
#define	_DeleteProfileRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OctetTo16.h"
#include "Iccid.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DeleteProfileRequest_PR {
	DeleteProfileRequest_PR_NOTHING,	/* No components present */
	DeleteProfileRequest_PR_isdpAid,
	DeleteProfileRequest_PR_iccid
	/* Extensions may appear below */
	
} DeleteProfileRequest_PR;

/* DeleteProfileRequest */
typedef struct DeleteProfileRequest {
	DeleteProfileRequest_PR present;
	union DeleteProfileRequest_u {
		OctetTo16_t	 isdpAid;
		Iccid_t	 iccid;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DeleteProfileRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DeleteProfileRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _DeleteProfileRequest_H_ */
#include "asn_internal.h"
