/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_DeviceCapabilities_H_
#define	_DeviceCapabilities_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VersionType.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DeviceCapabilities */
typedef struct DeviceCapabilities {
	VersionType_t	*gsmSupportedRelease	/* OPTIONAL */;
	VersionType_t	*utranSupportedRelease	/* OPTIONAL */;
	VersionType_t	*cdma2000onexSupportedRelease	/* OPTIONAL */;
	VersionType_t	*cdma2000hrpdSupportedRelease	/* OPTIONAL */;
	VersionType_t	*cdma2000ehrpdSupportedRelease	/* OPTIONAL */;
	VersionType_t	*eutranSupportedRelease	/* OPTIONAL */;
	VersionType_t	*contactlessSupportedRelease	/* OPTIONAL */;
	VersionType_t	*rspCrlSupportedVersion	/* OPTIONAL */;
	VersionType_t	*rspRpmSupportedVersion	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DeviceCapabilities_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DeviceCapabilities;
extern asn_SEQUENCE_specifics_t asn_SPC_DeviceCapabilities_specs_1;
extern asn_TYPE_member_t asn_MBR_DeviceCapabilities_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _DeviceCapabilities_H_ */
#include "asn_internal.h"
