/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "DeviceInfo.h"

asn_TYPE_member_t asn_MBR_DeviceInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DeviceInfo, tac),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Octet8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tac"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DeviceInfo, deviceCapabilities),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DeviceCapabilities,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"deviceCapabilities"
		},
	{ ATF_POINTER, 1, offsetof(struct DeviceInfo, imei),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Octet8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"imei"
		},
};
static const int asn_MAP_DeviceInfo_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_DeviceInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DeviceInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* tac */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* deviceCapabilities */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* imei */
};
asn_SEQUENCE_specifics_t asn_SPC_DeviceInfo_specs_1 = {
	sizeof(struct DeviceInfo),
	offsetof(struct DeviceInfo, _asn_ctx),
	asn_MAP_DeviceInfo_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_DeviceInfo_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DeviceInfo = {
	"DeviceInfo",
	"DeviceInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_DeviceInfo_tags_1,
	sizeof(asn_DEF_DeviceInfo_tags_1)
		/sizeof(asn_DEF_DeviceInfo_tags_1[0]), /* 1 */
	asn_DEF_DeviceInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_DeviceInfo_tags_1)
		/sizeof(asn_DEF_DeviceInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DeviceInfo_1,
	3,	/* Elements count */
	&asn_SPC_DeviceInfo_specs_1	/* Additional specs */
};

