/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "DeviceCapabilities.h"

asn_TYPE_member_t asn_MBR_DeviceCapabilities_1[] = {
	{ ATF_POINTER, 9, offsetof(struct DeviceCapabilities, gsmSupportedRelease),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gsmSupportedRelease"
		},
	{ ATF_POINTER, 8, offsetof(struct DeviceCapabilities, utranSupportedRelease),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"utranSupportedRelease"
		},
	{ ATF_POINTER, 7, offsetof(struct DeviceCapabilities, cdma2000onexSupportedRelease),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cdma2000onexSupportedRelease"
		},
	{ ATF_POINTER, 6, offsetof(struct DeviceCapabilities, cdma2000hrpdSupportedRelease),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cdma2000hrpdSupportedRelease"
		},
	{ ATF_POINTER, 5, offsetof(struct DeviceCapabilities, cdma2000ehrpdSupportedRelease),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cdma2000ehrpdSupportedRelease"
		},
	{ ATF_POINTER, 4, offsetof(struct DeviceCapabilities, eutranSupportedRelease),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eutranSupportedRelease"
		},
	{ ATF_POINTER, 3, offsetof(struct DeviceCapabilities, contactlessSupportedRelease),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"contactlessSupportedRelease"
		},
	{ ATF_POINTER, 2, offsetof(struct DeviceCapabilities, rspCrlSupportedVersion),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rspCrlSupportedVersion"
		},
	{ ATF_POINTER, 1, offsetof(struct DeviceCapabilities, rspRpmSupportedVersion),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rspRpmSupportedVersion"
		},
};
static const int asn_MAP_DeviceCapabilities_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8 };
static const ber_tlv_tag_t asn_DEF_DeviceCapabilities_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DeviceCapabilities_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gsmSupportedRelease */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* utranSupportedRelease */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* cdma2000onexSupportedRelease */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* cdma2000hrpdSupportedRelease */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* cdma2000ehrpdSupportedRelease */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* eutranSupportedRelease */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* contactlessSupportedRelease */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* rspCrlSupportedVersion */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* rspRpmSupportedVersion */
};
asn_SEQUENCE_specifics_t asn_SPC_DeviceCapabilities_specs_1 = {
	sizeof(struct DeviceCapabilities),
	offsetof(struct DeviceCapabilities, _asn_ctx),
	asn_MAP_DeviceCapabilities_tag2el_1,
	9,	/* Count of tags in the map */
	asn_MAP_DeviceCapabilities_oms_1,	/* Optional members */
	9, 0,	/* Root/Additions */
	9,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DeviceCapabilities = {
	"DeviceCapabilities",
	"DeviceCapabilities",
	&asn_OP_SEQUENCE,
	asn_DEF_DeviceCapabilities_tags_1,
	sizeof(asn_DEF_DeviceCapabilities_tags_1)
		/sizeof(asn_DEF_DeviceCapabilities_tags_1[0]), /* 1 */
	asn_DEF_DeviceCapabilities_tags_1,	/* Same as above */
	sizeof(asn_DEF_DeviceCapabilities_tags_1)
		/sizeof(asn_DEF_DeviceCapabilities_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DeviceCapabilities_1,
	9,	/* Elements count */
	&asn_SPC_DeviceCapabilities_specs_1	/* Additional specs */
};

