/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_DisableProfileRequest_H_
#define	_DisableProfileRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"
#include "OctetTo16.h"
#include "Iccid.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DisableProfileRequest__profileIdentifier_PR {
	DisableProfileRequest__profileIdentifier_PR_NOTHING,	/* No components present */
	DisableProfileRequest__profileIdentifier_PR_isdpAid,
	DisableProfileRequest__profileIdentifier_PR_iccid
	/* Extensions may appear below */
	
} DisableProfileRequest__profileIdentifier_PR;

/* DisableProfileRequest */
typedef struct DisableProfileRequest {
	struct DisableProfileRequest__profileIdentifier {
		DisableProfileRequest__profileIdentifier_PR present;
		union DisableProfileRequest__profileIdentifier_u {
			OctetTo16_t	 isdpAid;
			Iccid_t	 iccid;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} profileIdentifier;
	BOOLEAN_t	 refreshFlag;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DisableProfileRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DisableProfileRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _DisableProfileRequest_H_ */
#include "asn_internal.h"
