/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_DownloadErrorCode_H_
#define	_DownloadErrorCode_H_


#include "asn_application.h"

/* Including external dependencies */
#include "INTEGER.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DownloadErrorCode {
	DownloadErrorCode_invalidCertificate	= 1,
	DownloadErrorCode_invalidSignature	= 2,
	DownloadErrorCode_unsupportedCurve	= 3,
	DownloadErrorCode_noSessionContext	= 4,
	DownloadErrorCode_invalidTransactionId	= 5,
	DownloadErrorCode_undefinedError	= 127
} e_DownloadErrorCode;

/* DownloadErrorCode */
typedef INTEGER_t	 DownloadErrorCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DownloadErrorCode;
asn_struct_free_f DownloadErrorCode_free;
asn_struct_print_f DownloadErrorCode_print;
asn_constr_check_f DownloadErrorCode_constraint;
ber_type_decoder_f DownloadErrorCode_decode_ber;
der_type_encoder_f DownloadErrorCode_encode_der;
xer_type_decoder_f DownloadErrorCode_decode_xer;
xer_type_encoder_f DownloadErrorCode_encode_xer;
oer_type_decoder_f DownloadErrorCode_decode_oer;
oer_type_encoder_f DownloadErrorCode_encode_oer;
per_type_decoder_f DownloadErrorCode_decode_uper;
per_type_encoder_f DownloadErrorCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DownloadErrorCode_H_ */
#include "asn_internal.h"
