/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_DpProprietaryData_H_
#define	_DpProprietaryData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OBJECT_IDENTIFIER.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DpProprietaryData */
typedef struct DpProprietaryData {
	OBJECT_IDENTIFIER_t	 dpOid;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DpProprietaryData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DpProprietaryData;
extern asn_SEQUENCE_specifics_t asn_SPC_DpProprietaryData_specs_1;
extern asn_TYPE_member_t asn_MBR_DpProprietaryData_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _DpProprietaryData_H_ */
#include "asn_internal.h"
