/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_EnableProfileRequest_H_
#define	_EnableProfileRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"
#include "OctetTo16.h"
#include "Iccid.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EnableProfileRequest__profileIdentifier_PR {
	EnableProfileRequest__profileIdentifier_PR_NOTHING,	/* No components present */
	EnableProfileRequest__profileIdentifier_PR_isdpAid,
	EnableProfileRequest__profileIdentifier_PR_iccid
	/* Extensions may appear below */
	
} EnableProfileRequest__profileIdentifier_PR;

/* EnableProfileRequest */
typedef struct EnableProfileRequest {
	struct EnableProfileRequest__profileIdentifier {
		EnableProfileRequest__profileIdentifier_PR present;
		union EnableProfileRequest__profileIdentifier_u {
			OctetTo16_t	 isdpAid;
			Iccid_t	 iccid;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} profileIdentifier;
	BOOLEAN_t	 refreshFlag;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EnableProfileRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnableProfileRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _EnableProfileRequest_H_ */
#include "asn_internal.h"
