/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_EuiccCancelSessionSigned_H_
#define	_EuiccCancelSessionSigned_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TransactionId.h"
#include "OBJECT_IDENTIFIER.h"
#include "CancelSessionReason.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EuiccCancelSessionSigned */
typedef struct EuiccCancelSessionSigned {
	TransactionId_t	 transactionId;
	OBJECT_IDENTIFIER_t	 smdpOid;
	CancelSessionReason_t	 reason;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EuiccCancelSessionSigned_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EuiccCancelSessionSigned;
extern asn_SEQUENCE_specifics_t asn_SPC_EuiccCancelSessionSigned_specs_1;
extern asn_TYPE_member_t asn_MBR_EuiccCancelSessionSigned_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _EuiccCancelSessionSigned_H_ */
#include "asn_internal.h"
