/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_EuiccSignPIR_H_
#define	_EuiccSignPIR_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EuiccSignPIR */
typedef OCTET_STRING_t	 EuiccSignPIR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EuiccSignPIR;
asn_struct_free_f EuiccSignPIR_free;
asn_struct_print_f EuiccSignPIR_print;
asn_constr_check_f EuiccSignPIR_constraint;
ber_type_decoder_f EuiccSignPIR_decode_ber;
der_type_encoder_f EuiccSignPIR_encode_der;
xer_type_decoder_f EuiccSignPIR_decode_xer;
xer_type_encoder_f EuiccSignPIR_encode_xer;
oer_type_decoder_f EuiccSignPIR_decode_oer;
oer_type_encoder_f EuiccSignPIR_encode_oer;
per_type_decoder_f EuiccSignPIR_decode_uper;
per_type_encoder_f EuiccSignPIR_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EuiccSignPIR_H_ */
#include "asn_internal.h"
