/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "EUICCInfo2.h"

static int
memb_sasAcreditationNumber_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 64)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_sasAcreditationNumber_constr_21 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_sasAcreditationNumber_constr_21 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_euiccCiPKIdListForVerification_10[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_SubjectKeyIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_euiccCiPKIdListForVerification_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_euiccCiPKIdListForVerification_specs_10 = {
	sizeof(struct EUICCInfo2__euiccCiPKIdListForVerification),
	offsetof(struct EUICCInfo2__euiccCiPKIdListForVerification, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_euiccCiPKIdListForVerification_10 = {
	"euiccCiPKIdListForVerification",
	"euiccCiPKIdListForVerification",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_euiccCiPKIdListForVerification_tags_10,
	sizeof(asn_DEF_euiccCiPKIdListForVerification_tags_10)
		/sizeof(asn_DEF_euiccCiPKIdListForVerification_tags_10[0]) - 1, /* 1 */
	asn_DEF_euiccCiPKIdListForVerification_tags_10,	/* Same as above */
	sizeof(asn_DEF_euiccCiPKIdListForVerification_tags_10)
		/sizeof(asn_DEF_euiccCiPKIdListForVerification_tags_10[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_euiccCiPKIdListForVerification_10,
	1,	/* Single element */
	&asn_SPC_euiccCiPKIdListForVerification_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_euiccCiPKIdListForSigning_12[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_SubjectKeyIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_euiccCiPKIdListForSigning_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_euiccCiPKIdListForSigning_specs_12 = {
	sizeof(struct EUICCInfo2__euiccCiPKIdListForSigning),
	offsetof(struct EUICCInfo2__euiccCiPKIdListForSigning, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_euiccCiPKIdListForSigning_12 = {
	"euiccCiPKIdListForSigning",
	"euiccCiPKIdListForSigning",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_euiccCiPKIdListForSigning_tags_12,
	sizeof(asn_DEF_euiccCiPKIdListForSigning_tags_12)
		/sizeof(asn_DEF_euiccCiPKIdListForSigning_tags_12[0]) - 1, /* 1 */
	asn_DEF_euiccCiPKIdListForSigning_tags_12,	/* Same as above */
	sizeof(asn_DEF_euiccCiPKIdListForSigning_tags_12)
		/sizeof(asn_DEF_euiccCiPKIdListForSigning_tags_12[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_euiccCiPKIdListForSigning_12,
	1,	/* Single element */
	&asn_SPC_euiccCiPKIdListForSigning_specs_12	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_EUICCInfo2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EUICCInfo2, profileVersion),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileVersion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EUICCInfo2, svn),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"svn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EUICCInfo2, euiccFirmwareVer),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccFirmwareVer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EUICCInfo2, extCardResource),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extCardResource"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EUICCInfo2, uiccCapability),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UICCCapability,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uiccCapability"
		},
	{ ATF_POINTER, 2, offsetof(struct EUICCInfo2, javacardVersion),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"javacardVersion"
		},
	{ ATF_POINTER, 1, offsetof(struct EUICCInfo2, globalplatformVersion),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"globalplatformVersion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EUICCInfo2, rspCapability),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RspCapability,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rspCapability"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EUICCInfo2, euiccCiPKIdListForVerification),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		0,
		&asn_DEF_euiccCiPKIdListForVerification_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccCiPKIdListForVerification"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EUICCInfo2, euiccCiPKIdListForSigning),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		0,
		&asn_DEF_euiccCiPKIdListForSigning_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccCiPKIdListForSigning"
		},
	{ ATF_POINTER, 2, offsetof(struct EUICCInfo2, euiccCategory),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccCategory"
		},
	{ ATF_POINTER, 1, offsetof(struct EUICCInfo2, forbiddenProfilePolicyRules),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PprIds,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"forbiddenProfilePolicyRules"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EUICCInfo2, ppVersion),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ppVersion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EUICCInfo2, sasAcreditationNumber),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_sasAcreditationNumber_constr_21, &asn_PER_memb_sasAcreditationNumber_constr_21,  memb_sasAcreditationNumber_constraint_1 },
		0, 0, /* No default value */
		"sasAcreditationNumber"
		},
	{ ATF_POINTER, 1, offsetof(struct EUICCInfo2, certificationDataObject),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CertificationDataObject,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certificationDataObject"
		},
};
static const int asn_MAP_EUICCInfo2_oms_1[] = { 5, 6, 10, 11, 14 };
static const ber_tlv_tag_t asn_DEF_EUICCInfo2_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (34 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EUICCInfo2_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 12, 0, 0 }, /* ppVersion */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 13, 0, 0 }, /* sasAcreditationNumber */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* profileVersion */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* svn */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* euiccFirmwareVer */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* extCardResource */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* uiccCapability */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* javacardVersion */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* globalplatformVersion */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 7, 0, 0 }, /* rspCapability */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 8, 0, 0 }, /* euiccCiPKIdListForVerification */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 9, 0, 0 }, /* euiccCiPKIdListForSigning */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 10, 0, 0 }, /* euiccCategory */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 14, 0, 0 }, /* certificationDataObject */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 11, 0, 0 } /* forbiddenProfilePolicyRules */
};
asn_SEQUENCE_specifics_t asn_SPC_EUICCInfo2_specs_1 = {
	sizeof(struct EUICCInfo2),
	offsetof(struct EUICCInfo2, _asn_ctx),
	asn_MAP_EUICCInfo2_tag2el_1,
	15,	/* Count of tags in the map */
	asn_MAP_EUICCInfo2_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	15,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EUICCInfo2 = {
	"EUICCInfo2",
	"EUICCInfo2",
	&asn_OP_SEQUENCE,
	asn_DEF_EUICCInfo2_tags_1,
	sizeof(asn_DEF_EUICCInfo2_tags_1)
		/sizeof(asn_DEF_EUICCInfo2_tags_1[0]) - 1, /* 1 */
	asn_DEF_EUICCInfo2_tags_1,	/* Same as above */
	sizeof(asn_DEF_EUICCInfo2_tags_1)
		/sizeof(asn_DEF_EUICCInfo2_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EUICCInfo2_1,
	15,	/* Elements count */
	&asn_SPC_EUICCInfo2_specs_1	/* Additional specs */
};

