/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_EUICCInfo1_H_
#define	_EUICCInfo1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VersionType.h"
#include "SubjectKeyIdentifier.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EUICCInfo1 */
typedef struct EUICCInfo1 {
	VersionType_t	 svn;
	struct EUICCInfo1__euiccCiPKIdListForVerification {
		A_SEQUENCE_OF(SubjectKeyIdentifier_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} euiccCiPKIdListForVerification;
	struct EUICCInfo1__euiccCiPKIdListForSigning {
		A_SEQUENCE_OF(SubjectKeyIdentifier_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} euiccCiPKIdListForSigning;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUICCInfo1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EUICCInfo1;
extern asn_SEQUENCE_specifics_t asn_SPC_EUICCInfo1_specs_1;
extern asn_TYPE_member_t asn_MBR_EUICCInfo1_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _EUICCInfo1_H_ */
#include "asn_internal.h"
