/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_GetBoundProfilePackageOk_H_
#define	_GetBoundProfilePackageOk_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TransactionId.h"
#include "BoundProfilePackage.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GetBoundProfilePackageOk */
typedef struct GetBoundProfilePackageOk {
	TransactionId_t	 transactionId;
	BoundProfilePackage_t	 boundProfilePackage;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetBoundProfilePackageOk_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetBoundProfilePackageOk;
extern asn_SEQUENCE_specifics_t asn_SPC_GetBoundProfilePackageOk_specs_1;
extern asn_TYPE_member_t asn_MBR_GetBoundProfilePackageOk_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _GetBoundProfilePackageOk_H_ */
#include "asn_internal.h"
