/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_GetRatRequest_H_
#define	_GetRatRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GetRatRequest */
typedef struct GetRatRequest {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetRatRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetRatRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _GetRatRequest_H_ */
#include "asn_internal.h"
