/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_IconType_H_
#define	_IconType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "INTEGER.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IconType {
	IconType_jpg	= 0,
	IconType_png	= 1
} e_IconType;

/* IconType */
typedef INTEGER_t	 IconType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IconType;
asn_struct_free_f IconType_free;
asn_struct_print_f IconType_print;
asn_constr_check_f IconType_constraint;
ber_type_decoder_f IconType_decode_ber;
der_type_encoder_f IconType_encode_der;
xer_type_decoder_f IconType_decode_xer;
xer_type_encoder_f IconType_encode_xer;
oer_type_decoder_f IconType_decode_oer;
oer_type_encoder_f IconType_encode_oer;
per_type_decoder_f IconType_decode_uper;
per_type_encoder_f IconType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _IconType_H_ */
#include "asn_internal.h"
