/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_InitiateAuthenticationRequest_H_
#define	_InitiateAuthenticationRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Octet16.h"
#include "UTF8String.h"
#include "EUICCInfo1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* InitiateAuthenticationRequest */
typedef struct InitiateAuthenticationRequest {
	Octet16_t	 euiccChallenge;
	UTF8String_t	 smdpAddress;
	EUICCInfo1_t	 euiccInfo1;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitiateAuthenticationRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitiateAuthenticationRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_InitiateAuthenticationRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_InitiateAuthenticationRequest_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _InitiateAuthenticationRequest_H_ */
#include "asn_internal.h"
