/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_InitiateAuthenticationOkEs9_H_
#define	_InitiateAuthenticationOkEs9_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TransactionId.h"
#include "ServerSigned1.h"
#include "OCTET_STRING.h"
#include "SubjectKeyIdentifier.h"
#include "Certificate.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* InitiateAuthenticationOkEs9 */
typedef struct InitiateAuthenticationOkEs9 {
	TransactionId_t	 transactionId;
	ServerSigned1_t	 serverSigned1;
	OCTET_STRING_t	 serverSignature1;
	SubjectKeyIdentifier_t	 euiccCiPKIdToBeUsed;
	Certificate_t	 serverCertificate;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitiateAuthenticationOkEs9_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitiateAuthenticationOkEs9;
extern asn_SEQUENCE_specifics_t asn_SPC_InitiateAuthenticationOkEs9_specs_1;
extern asn_TYPE_member_t asn_MBR_InitiateAuthenticationOkEs9_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _InitiateAuthenticationOkEs9_H_ */
#include "asn_internal.h"
