/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "InitialiseSecureChannelRequest.h"

asn_TYPE_member_t asn_MBR_InitialiseSecureChannelRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InitialiseSecureChannelRequest, remoteOpId),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_RemoteOpId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"remoteOpId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitialiseSecureChannelRequest, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitialiseSecureChannelRequest, controlRefTemplate),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ControlRefTemplate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"controlRefTemplate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitialiseSecureChannelRequest, smdpOtpk),
		(ASN_TAG_CLASS_APPLICATION | (73 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpOtpk"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitialiseSecureChannelRequest, smdpSign),
		(ASN_TAG_CLASS_APPLICATION | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSign"
		},
};
static const ber_tlv_tag_t asn_DEF_InitialiseSecureChannelRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (35 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_InitialiseSecureChannelRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (55 << 2)), 4, 0, 0 }, /* smdpSign */
    { (ASN_TAG_CLASS_APPLICATION | (73 << 2)), 3, 0, 0 }, /* smdpOtpk */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* transactionId */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* remoteOpId */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 2, 0, 0 } /* controlRefTemplate */
};
asn_SEQUENCE_specifics_t asn_SPC_InitialiseSecureChannelRequest_specs_1 = {
	sizeof(struct InitialiseSecureChannelRequest),
	offsetof(struct InitialiseSecureChannelRequest, _asn_ctx),
	asn_MAP_InitialiseSecureChannelRequest_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_InitialiseSecureChannelRequest = {
	"InitialiseSecureChannelRequest",
	"InitialiseSecureChannelRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_InitialiseSecureChannelRequest_tags_1,
	sizeof(asn_DEF_InitialiseSecureChannelRequest_tags_1)
		/sizeof(asn_DEF_InitialiseSecureChannelRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_InitialiseSecureChannelRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_InitialiseSecureChannelRequest_tags_1)
		/sizeof(asn_DEF_InitialiseSecureChannelRequest_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_InitialiseSecureChannelRequest_1,
	5,	/* Elements count */
	&asn_SPC_InitialiseSecureChannelRequest_specs_1	/* Additional specs */
};

