/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ISDRProprietaryApplicationTemplate_H_
#define	_ISDRProprietaryApplicationTemplate_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VersionType.h"
#include "BIT_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ISDRProprietaryApplicationTemplate__lpaeSupport {
	ISDRProprietaryApplicationTemplate__lpaeSupport_lpaeUsingCat	= 0,
	ISDRProprietaryApplicationTemplate__lpaeSupport_lpaeUsingScws	= 1
} e_ISDRProprietaryApplicationTemplate__lpaeSupport;

/* ISDRProprietaryApplicationTemplate */
typedef struct ISDRProprietaryApplicationTemplate {
	VersionType_t	 svn;
	BIT_STRING_t	*lpaeSupport	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ISDRProprietaryApplicationTemplate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ISDRProprietaryApplicationTemplate;

#ifdef __cplusplus
}
#endif

#endif	/* _ISDRProprietaryApplicationTemplate_H_ */
#include "asn_internal.h"
