/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_LoadCRLResponseError_H_
#define	_LoadCRLResponseError_H_


#include "asn_application.h"

/* Including external dependencies */
#include "INTEGER.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LoadCRLResponseError {
	LoadCRLResponseError_invalidSignature	= 1,
	LoadCRLResponseError_invalidCRLFormat	= 2,
	LoadCRLResponseError_notEnoughMemorySpace	= 3,
	LoadCRLResponseError_verificationKeyNotFound	= 4,
	LoadCRLResponseError_undefinedError	= 127
} e_LoadCRLResponseError;

/* LoadCRLResponseError */
typedef INTEGER_t	 LoadCRLResponseError_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoadCRLResponseError;
asn_struct_free_f LoadCRLResponseError_free;
asn_struct_print_f LoadCRLResponseError_print;
asn_constr_check_f LoadCRLResponseError_constraint;
ber_type_decoder_f LoadCRLResponseError_decode_ber;
der_type_encoder_f LoadCRLResponseError_encode_der;
xer_type_decoder_f LoadCRLResponseError_decode_xer;
xer_type_encoder_f LoadCRLResponseError_encode_xer;
oer_type_decoder_f LoadCRLResponseError_decode_oer;
oer_type_encoder_f LoadCRLResponseError_encode_oer;
per_type_decoder_f LoadCRLResponseError_decode_uper;
per_type_encoder_f LoadCRLResponseError_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LoadCRLResponseError_H_ */
#include "asn_internal.h"
