/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_LoadCRLResponseOk_H_
#define	_LoadCRLResponseOk_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "INTEGER.h"
#include "constr_SEQUENCE.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct LoadCRLResponseOk__missingParts__Member {
	INTEGER_t	 number;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LoadCRLResponseOk__missingParts__Member;

/* LoadCRLResponseOk */
typedef struct LoadCRLResponseOk {
	struct LoadCRLResponseOk__missingParts {
		A_SEQUENCE_OF(LoadCRLResponseOk__missingParts__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *missingParts;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LoadCRLResponseOk_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoadCRLResponseOk;
extern asn_SEQUENCE_specifics_t asn_SPC_LoadCRLResponseOk_specs_1;
extern asn_TYPE_member_t asn_MBR_LoadCRLResponseOk_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _LoadCRLResponseOk_H_ */
#include "asn_internal.h"
