/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_NotificationEvent_H_
#define	_NotificationEvent_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NotificationEvent {
	NotificationEvent_notificationInstall	= 0,
	NotificationEvent_notificationEnable	= 1,
	NotificationEvent_notificationDisable	= 2,
	NotificationEvent_notificationDelete	= 3
} e_NotificationEvent;

/* NotificationEvent */
typedef BIT_STRING_t	 NotificationEvent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NotificationEvent;
asn_struct_free_f NotificationEvent_free;
asn_struct_print_f NotificationEvent_print;
asn_constr_check_f NotificationEvent_constraint;
ber_type_decoder_f NotificationEvent_decode_ber;
der_type_encoder_f NotificationEvent_encode_der;
xer_type_decoder_f NotificationEvent_decode_xer;
xer_type_encoder_f NotificationEvent_encode_xer;
oer_type_decoder_f NotificationEvent_decode_oer;
oer_type_encoder_f NotificationEvent_encode_oer;
per_type_decoder_f NotificationEvent_decode_uper;
per_type_encoder_f NotificationEvent_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NotificationEvent_H_ */
#include "asn_internal.h"
