/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_NotificationMetadata_H_
#define	_NotificationMetadata_H_


#include "asn_application.h"

/* Including external dependencies */
#include "INTEGER.h"
#include "NotificationEvent.h"
#include "UTF8String.h"
#include "Iccid.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NotificationMetadata */
typedef struct NotificationMetadata {
	INTEGER_t	 seqNumber;
	NotificationEvent_t	 profileManagementOperation;
	UTF8String_t	 notificationAddress;
	Iccid_t	*iccid	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NotificationMetadata_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NotificationMetadata;
extern asn_SEQUENCE_specifics_t asn_SPC_NotificationMetadata_specs_1;
extern asn_TYPE_member_t asn_MBR_NotificationMetadata_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NotificationMetadata_H_ */
#include "asn_internal.h"
