/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "NotificationMetadata.h"

asn_TYPE_member_t asn_MBR_NotificationMetadata_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NotificationMetadata, seqNumber),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"seqNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NotificationMetadata, profileManagementOperation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NotificationEvent,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileManagementOperation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NotificationMetadata, notificationAddress),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notificationAddress"
		},
	{ ATF_POINTER, 1, offsetof(struct NotificationMetadata, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		0,
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
};
static const int asn_MAP_NotificationMetadata_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_NotificationMetadata_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (47 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NotificationMetadata_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 2, 0, 0 }, /* notificationAddress */
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 3, 0, 0 }, /* iccid */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* seqNumber */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* profileManagementOperation */
};
asn_SEQUENCE_specifics_t asn_SPC_NotificationMetadata_specs_1 = {
	sizeof(struct NotificationMetadata),
	offsetof(struct NotificationMetadata, _asn_ctx),
	asn_MAP_NotificationMetadata_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_NotificationMetadata_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NotificationMetadata = {
	"NotificationMetadata",
	"NotificationMetadata",
	&asn_OP_SEQUENCE,
	asn_DEF_NotificationMetadata_tags_1,
	sizeof(asn_DEF_NotificationMetadata_tags_1)
		/sizeof(asn_DEF_NotificationMetadata_tags_1[0]) - 1, /* 1 */
	asn_DEF_NotificationMetadata_tags_1,	/* Same as above */
	sizeof(asn_DEF_NotificationMetadata_tags_1)
		/sizeof(asn_DEF_NotificationMetadata_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NotificationMetadata_1,
	4,	/* Elements count */
	&asn_SPC_NotificationMetadata_specs_1	/* Additional specs */
};

