/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_Octet16_H_
#define	_Octet16_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Octet16 */
typedef OCTET_STRING_t	 Octet16_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Octet16_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Octet16;
asn_struct_free_f Octet16_free;
asn_struct_print_f Octet16_print;
asn_constr_check_f Octet16_constraint;
ber_type_decoder_f Octet16_decode_ber;
der_type_encoder_f Octet16_encode_der;
xer_type_decoder_f Octet16_decode_xer;
xer_type_encoder_f Octet16_encode_xer;
oer_type_decoder_f Octet16_decode_oer;
oer_type_encoder_f Octet16_encode_oer;
per_type_decoder_f Octet16_decode_uper;
per_type_encoder_f Octet16_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Octet16_H_ */
#include "asn_internal.h"
