/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "OperatorID.h"

static int
memb_mccMnc_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_mccMnc_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	3	/* (SIZE(3..3)) */};
static asn_per_constraints_t asn_PER_memb_mccMnc_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  3,  3 }	/* (SIZE(3..3)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_OperatorID_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OperatorID, mccMnc),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_mccMnc_constr_2, &asn_PER_memb_mccMnc_constr_2,  memb_mccMnc_constraint_1 },
		0, 0, /* No default value */
		"mccMnc"
		},
	{ ATF_POINTER, 2, offsetof(struct OperatorID, gid1),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gid1"
		},
	{ ATF_POINTER, 1, offsetof(struct OperatorID, gid2),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gid2"
		},
};
static const int asn_MAP_OperatorID_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_OperatorID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_OperatorID_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mccMnc */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* gid1 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* gid2 */
};
asn_SEQUENCE_specifics_t asn_SPC_OperatorID_specs_1 = {
	sizeof(struct OperatorID),
	offsetof(struct OperatorID, _asn_ctx),
	asn_MAP_OperatorID_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_OperatorID_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_OperatorID = {
	"OperatorID",
	"OperatorID",
	&asn_OP_SEQUENCE,
	asn_DEF_OperatorID_tags_1,
	sizeof(asn_DEF_OperatorID_tags_1)
		/sizeof(asn_DEF_OperatorID_tags_1[0]), /* 1 */
	asn_DEF_OperatorID_tags_1,	/* Same as above */
	sizeof(asn_DEF_OperatorID_tags_1)
		/sizeof(asn_DEF_OperatorID_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_OperatorID_1,
	3,	/* Elements count */
	&asn_SPC_OperatorID_specs_1	/* Additional specs */
};

