/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "OtherSignedNotification.h"

asn_TYPE_member_t asn_MBR_OtherSignedNotification_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OtherSignedNotification, tbsOtherNotification),
		(ASN_TAG_CLASS_CONTEXT | (47 << 2)),
		0,
		&asn_DEF_NotificationMetadata,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tbsOtherNotification"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OtherSignedNotification, euiccNotificationSignature),
		(ASN_TAG_CLASS_APPLICATION | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccNotificationSignature"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OtherSignedNotification, euiccCertificate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Certificate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccCertificate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OtherSignedNotification, eumCertificate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Certificate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eumCertificate"
		},
};
static const ber_tlv_tag_t asn_DEF_OtherSignedNotification_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_OtherSignedNotification_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 1 }, /* euiccCertificate */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -1, 0 }, /* eumCertificate */
    { (ASN_TAG_CLASS_APPLICATION | (55 << 2)), 1, 0, 0 }, /* euiccNotificationSignature */
    { (ASN_TAG_CLASS_CONTEXT | (47 << 2)), 0, 0, 0 } /* tbsOtherNotification */
};
asn_SEQUENCE_specifics_t asn_SPC_OtherSignedNotification_specs_1 = {
	sizeof(struct OtherSignedNotification),
	offsetof(struct OtherSignedNotification, _asn_ctx),
	asn_MAP_OtherSignedNotification_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_OtherSignedNotification = {
	"OtherSignedNotification",
	"OtherSignedNotification",
	&asn_OP_SEQUENCE,
	asn_DEF_OtherSignedNotification_tags_1,
	sizeof(asn_DEF_OtherSignedNotification_tags_1)
		/sizeof(asn_DEF_OtherSignedNotification_tags_1[0]), /* 1 */
	asn_DEF_OtherSignedNotification_tags_1,	/* Same as above */
	sizeof(asn_DEF_OtherSignedNotification_tags_1)
		/sizeof(asn_DEF_OtherSignedNotification_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_OtherSignedNotification_1,
	4,	/* Elements count */
	&asn_SPC_OtherSignedNotification_specs_1	/* Additional specs */
};

