/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PendingNotification_H_
#define	_PendingNotification_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ProfileInstallationResult.h"
#include "OtherSignedNotification.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PendingNotification_PR {
	PendingNotification_PR_NOTHING,	/* No components present */
	PendingNotification_PR_profileInstallationResult,
	PendingNotification_PR_otherSignedNotification
	/* Extensions may appear below */
	
} PendingNotification_PR;

/* PendingNotification */
typedef struct PendingNotification {
	PendingNotification_PR present;
	union PendingNotification_u {
		ProfileInstallationResult_t	 profileInstallationResult;
		OtherSignedNotification_t	 otherSignedNotification;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PendingNotification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PendingNotification;
extern asn_CHOICE_specifics_t asn_SPC_PendingNotification_specs_1;
extern asn_TYPE_member_t asn_MBR_PendingNotification_1[2];
extern asn_per_constraints_t asn_PER_type_PendingNotification_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PendingNotification_H_ */
#include "asn_internal.h"
