/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PrepareDownloadRequest_H_
#define	_PrepareDownloadRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SmdpSigned2.h"
#include "OCTET_STRING.h"
#include "Octet32.h"
#include "Certificate.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PrepareDownloadRequest */
typedef struct PrepareDownloadRequest {
	SmdpSigned2_t	 smdpSigned2;
	OCTET_STRING_t	 smdpSignature2;
	Octet32_t	*hashCc	/* OPTIONAL */;
	Certificate_t	 smdpCertificate;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrepareDownloadRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrepareDownloadRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_PrepareDownloadRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_PrepareDownloadRequest_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _PrepareDownloadRequest_H_ */
#include "asn_internal.h"
