/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "PrepareDownloadResponse.h"

static asn_oer_constraints_t asn_OER_type_PrepareDownloadResponse_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_PrepareDownloadResponse_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_PrepareDownloadResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PrepareDownloadResponse, choice.downloadResponseOk),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrepareDownloadResponseOk,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"downloadResponseOk"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PrepareDownloadResponse, choice.downloadResponseError),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrepareDownloadResponseError,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"downloadResponseError"
		},
};
static const ber_tlv_tag_t asn_DEF_PrepareDownloadResponse_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (33 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PrepareDownloadResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* downloadResponseOk */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* downloadResponseError */
};
asn_CHOICE_specifics_t asn_SPC_PrepareDownloadResponse_specs_1 = {
	sizeof(struct PrepareDownloadResponse),
	offsetof(struct PrepareDownloadResponse, _asn_ctx),
	offsetof(struct PrepareDownloadResponse, present),
	sizeof(((struct PrepareDownloadResponse *)0)->present),
	asn_MAP_PrepareDownloadResponse_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_PrepareDownloadResponse = {
	"PrepareDownloadResponse",
	"PrepareDownloadResponse",
	&asn_OP_CHOICE,
	asn_DEF_PrepareDownloadResponse_tags_1,
	sizeof(asn_DEF_PrepareDownloadResponse_tags_1)
		/sizeof(asn_DEF_PrepareDownloadResponse_tags_1[0]), /* 1 */
	asn_DEF_PrepareDownloadResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_PrepareDownloadResponse_tags_1)
		/sizeof(asn_DEF_PrepareDownloadResponse_tags_1[0]), /* 1 */
	{ &asn_OER_type_PrepareDownloadResponse_constr_1, &asn_PER_type_PrepareDownloadResponse_constr_1, CHOICE_constraint },
	asn_MBR_PrepareDownloadResponse_1,
	2,	/* Elements count */
	&asn_SPC_PrepareDownloadResponse_specs_1	/* Additional specs */
};

