/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PrepareDownloadResponse_H_
#define	_PrepareDownloadResponse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PrepareDownloadResponseOk.h"
#include "PrepareDownloadResponseError.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PrepareDownloadResponse_PR {
	PrepareDownloadResponse_PR_NOTHING,	/* No components present */
	PrepareDownloadResponse_PR_downloadResponseOk,
	PrepareDownloadResponse_PR_downloadResponseError
	/* Extensions may appear below */
	
} PrepareDownloadResponse_PR;

/* PrepareDownloadResponse */
typedef struct PrepareDownloadResponse {
	PrepareDownloadResponse_PR present;
	union PrepareDownloadResponse_u {
		PrepareDownloadResponseOk_t	 downloadResponseOk;
		PrepareDownloadResponseError_t	 downloadResponseError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrepareDownloadResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrepareDownloadResponse;
extern asn_CHOICE_specifics_t asn_SPC_PrepareDownloadResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_PrepareDownloadResponse_1[2];
extern asn_per_constraints_t asn_PER_type_PrepareDownloadResponse_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PrepareDownloadResponse_H_ */
#include "asn_internal.h"
