/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PrepareDownloadResponseOk_H_
#define	_PrepareDownloadResponseOk_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EUICCSigned2.h"
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PrepareDownloadResponseOk */
typedef struct PrepareDownloadResponseOk {
	EUICCSigned2_t	 euiccSigned2;
	OCTET_STRING_t	 euiccSignature2;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrepareDownloadResponseOk_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrepareDownloadResponseOk;
extern asn_SEQUENCE_specifics_t asn_SPC_PrepareDownloadResponseOk_specs_1;
extern asn_TYPE_member_t asn_MBR_PrepareDownloadResponseOk_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PrepareDownloadResponseOk_H_ */
#include "asn_internal.h"
