/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "ProfileInstallationResultData.h"

static asn_oer_constraints_t asn_OER_type_finalResult_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_finalResult_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_finalResult_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileInstallationResultData__finalResult, choice.successResult),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SuccessResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"successResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileInstallationResultData__finalResult, choice.errorResult),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ErrorResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"errorResult"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_finalResult_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* successResult */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* errorResult */
};
static asn_CHOICE_specifics_t asn_SPC_finalResult_specs_5 = {
	sizeof(struct ProfileInstallationResultData__finalResult),
	offsetof(struct ProfileInstallationResultData__finalResult, _asn_ctx),
	offsetof(struct ProfileInstallationResultData__finalResult, present),
	sizeof(((struct ProfileInstallationResultData__finalResult *)0)->present),
	asn_MAP_finalResult_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_finalResult_5 = {
	"finalResult",
	"finalResult",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_finalResult_constr_5, &asn_PER_type_finalResult_constr_5, CHOICE_constraint },
	asn_MBR_finalResult_5,
	2,	/* Elements count */
	&asn_SPC_finalResult_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProfileInstallationResultData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileInstallationResultData, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileInstallationResultData, notificationMetadata),
		(ASN_TAG_CLASS_CONTEXT | (47 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NotificationMetadata,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notificationMetadata"
		},
	{ ATF_POINTER, 1, offsetof(struct ProfileInstallationResultData, smdpOid),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpOid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileInstallationResultData, finalResult),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_finalResult_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"finalResult"
		},
};
static const int asn_MAP_ProfileInstallationResultData_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_ProfileInstallationResultData_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (39 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ProfileInstallationResultData_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 2, 0, 0 }, /* smdpOid */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* transactionId */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 }, /* finalResult */
    { (ASN_TAG_CLASS_CONTEXT | (47 << 2)), 1, 0, 0 } /* notificationMetadata */
};
asn_SEQUENCE_specifics_t asn_SPC_ProfileInstallationResultData_specs_1 = {
	sizeof(struct ProfileInstallationResultData),
	offsetof(struct ProfileInstallationResultData, _asn_ctx),
	asn_MAP_ProfileInstallationResultData_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_ProfileInstallationResultData_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ProfileInstallationResultData = {
	"ProfileInstallationResultData",
	"ProfileInstallationResultData",
	&asn_OP_SEQUENCE,
	asn_DEF_ProfileInstallationResultData_tags_1,
	sizeof(asn_DEF_ProfileInstallationResultData_tags_1)
		/sizeof(asn_DEF_ProfileInstallationResultData_tags_1[0]) - 1, /* 1 */
	asn_DEF_ProfileInstallationResultData_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProfileInstallationResultData_tags_1)
		/sizeof(asn_DEF_ProfileInstallationResultData_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ProfileInstallationResultData_1,
	4,	/* Elements count */
	&asn_SPC_ProfileInstallationResultData_specs_1	/* Additional specs */
};

