/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "ProfileInfo.h"

static int
memb_profileNickname_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 64)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_serviceProviderName_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_profileName_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 64)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_icon_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size <= 1024)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_profileNickname_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_profileNickname_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_serviceProviderName_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_serviceProviderName_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_profileName_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_profileName_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_icon_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..1024)) */};
static asn_per_constraints_t asn_PER_memb_icon_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 11,  11,  0,  1024 }	/* (SIZE(0..1024)) */,
	0, 0	/* No PER value map */
};
static int asn_DFL_10_cmp_2(const void *sptr) {
	const ProfileClass_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 2 */
	long value;
	if(asn_INTEGER2long(st, &value))
		return -1;
	return (value != 2);
}
static int asn_DFL_10_set_2(void **sptr) {
	ProfileClass_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 2 */
	return asn_long2INTEGER(st, 2);
}
static asn_TYPE_member_t asn_MBR_notificationConfigurationInfo_11[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NotificationConfigurationInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_notificationConfigurationInfo_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_notificationConfigurationInfo_specs_11 = {
	sizeof(struct ProfileInfo__notificationConfigurationInfo),
	offsetof(struct ProfileInfo__notificationConfigurationInfo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_notificationConfigurationInfo_11 = {
	"notificationConfigurationInfo",
	"notificationConfigurationInfo",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_notificationConfigurationInfo_tags_11,
	sizeof(asn_DEF_notificationConfigurationInfo_tags_11)
		/sizeof(asn_DEF_notificationConfigurationInfo_tags_11[0]) - 1, /* 1 */
	asn_DEF_notificationConfigurationInfo_tags_11,	/* Same as above */
	sizeof(asn_DEF_notificationConfigurationInfo_tags_11)
		/sizeof(asn_DEF_notificationConfigurationInfo_tags_11[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_notificationConfigurationInfo_11,
	1,	/* Single element */
	&asn_SPC_notificationConfigurationInfo_specs_11	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_refArDo_16[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_PRIVATE | (2 << 2)),
		0,
		&asn_DEF_RefArDo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_refArDo_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (118 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_refArDo_specs_16 = {
	sizeof(struct ProfileInfo__refArDo),
	offsetof(struct ProfileInfo__refArDo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_refArDo_16 = {
	"refArDo",
	"refArDo",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_refArDo_tags_16,
	sizeof(asn_DEF_refArDo_tags_16)
		/sizeof(asn_DEF_refArDo_tags_16[0]) - 1, /* 1 */
	asn_DEF_refArDo_tags_16,	/* Same as above */
	sizeof(asn_DEF_refArDo_tags_16)
		/sizeof(asn_DEF_refArDo_tags_16[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_refArDo_16,
	1,	/* Single element */
	&asn_SPC_refArDo_specs_16	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProfileInfo_1[] = {
	{ ATF_POINTER, 14, offsetof(struct ProfileInfo, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		0,
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
	{ ATF_POINTER, 13, offsetof(struct ProfileInfo, isdpAid),
		(ASN_TAG_CLASS_APPLICATION | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OctetTo16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"isdpAid"
		},
	{ ATF_POINTER, 12, offsetof(struct ProfileInfo, profileState),
		(ASN_TAG_CLASS_CONTEXT | (112 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProfileState,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileState"
		},
	{ ATF_POINTER, 11, offsetof(struct ProfileInfo, profileNickname),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_profileNickname_constr_5, &asn_PER_memb_profileNickname_constr_5,  memb_profileNickname_constraint_1 },
		0, 0, /* No default value */
		"profileNickname"
		},
	{ ATF_POINTER, 10, offsetof(struct ProfileInfo, serviceProviderName),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_serviceProviderName_constr_6, &asn_PER_memb_serviceProviderName_constr_6,  memb_serviceProviderName_constraint_1 },
		0, 0, /* No default value */
		"serviceProviderName"
		},
	{ ATF_POINTER, 9, offsetof(struct ProfileInfo, profileName),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_profileName_constr_7, &asn_PER_memb_profileName_constr_7,  memb_profileName_constraint_1 },
		0, 0, /* No default value */
		"profileName"
		},
	{ ATF_POINTER, 8, offsetof(struct ProfileInfo, iconType),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IconType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iconType"
		},
	{ ATF_POINTER, 7, offsetof(struct ProfileInfo, icon),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_icon_constr_9, &asn_PER_memb_icon_constr_9,  memb_icon_constraint_1 },
		0, 0, /* No default value */
		"icon"
		},
	{ ATF_POINTER, 6, offsetof(struct ProfileInfo, profileClass),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProfileClass,
		0,
		{ 0, 0, 0 },
		&asn_DFL_10_cmp_2,	/* Compare DEFAULT 2 */
		&asn_DFL_10_set_2,	/* Set DEFAULT 2 */
		"profileClass"
		},
	{ ATF_POINTER, 5, offsetof(struct ProfileInfo, notificationConfigurationInfo),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		0,
		&asn_DEF_notificationConfigurationInfo_11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notificationConfigurationInfo"
		},
	{ ATF_POINTER, 4, offsetof(struct ProfileInfo, profileOwner),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OperatorID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileOwner"
		},
	{ ATF_POINTER, 3, offsetof(struct ProfileInfo, dpProprietaryData),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DpProprietaryData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dpProprietaryData"
		},
	{ ATF_POINTER, 2, offsetof(struct ProfileInfo, profilePolicyRules),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PprIds,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profilePolicyRules"
		},
	{ ATF_POINTER, 1, offsetof(struct ProfileInfo, refArDo),
		(ASN_TAG_CLASS_CONTEXT | (118 << 2)),
		0,
		&asn_DEF_refArDo_16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"refArDo"
		},
};
static const int asn_MAP_ProfileInfo_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 };
static const ber_tlv_tag_t asn_DEF_ProfileInfo_tags_1[] = {
	(ASN_TAG_CLASS_PRIVATE | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ProfileInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (15 << 2)), 1, 0, 0 }, /* isdpAid */
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 }, /* iccid */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 3, 0, 0 }, /* profileNickname */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 4, 0, 0 }, /* serviceProviderName */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 5, 0, 0 }, /* profileName */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 6, 0, 0 }, /* iconType */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 7, 0, 0 }, /* icon */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 8, 0, 0 }, /* profileClass */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 9, 0, 0 }, /* notificationConfigurationInfo */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 10, 0, 0 }, /* profileOwner */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 11, 0, 0 }, /* dpProprietaryData */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 12, 0, 0 }, /* profilePolicyRules */
    { (ASN_TAG_CLASS_CONTEXT | (112 << 2)), 2, 0, 0 }, /* profileState */
    { (ASN_TAG_CLASS_CONTEXT | (118 << 2)), 13, 0, 0 } /* refArDo */
};
asn_SEQUENCE_specifics_t asn_SPC_ProfileInfo_specs_1 = {
	sizeof(struct ProfileInfo),
	offsetof(struct ProfileInfo, _asn_ctx),
	asn_MAP_ProfileInfo_tag2el_1,
	14,	/* Count of tags in the map */
	asn_MAP_ProfileInfo_oms_1,	/* Optional members */
	14, 0,	/* Root/Additions */
	14,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ProfileInfo = {
	"ProfileInfo",
	"ProfileInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_ProfileInfo_tags_1,
	sizeof(asn_DEF_ProfileInfo_tags_1)
		/sizeof(asn_DEF_ProfileInfo_tags_1[0]) - 1, /* 1 */
	asn_DEF_ProfileInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProfileInfo_tags_1)
		/sizeof(asn_DEF_ProfileInfo_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ProfileInfo_1,
	14,	/* Elements count */
	&asn_SPC_ProfileInfo_specs_1	/* Additional specs */
};

