/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ProfileInfoListError_H_
#define	_ProfileInfoListError_H_


#include "asn_application.h"

/* Including external dependencies */
#include "INTEGER.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProfileInfoListError {
	ProfileInfoListError_incorrectInputValues	= 1,
	ProfileInfoListError_undefinedError	= 127
} e_ProfileInfoListError;

/* ProfileInfoListError */
typedef INTEGER_t	 ProfileInfoListError_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProfileInfoListError;
asn_struct_free_f ProfileInfoListError_free;
asn_struct_print_f ProfileInfoListError_print;
asn_constr_check_f ProfileInfoListError_constraint;
ber_type_decoder_f ProfileInfoListError_decode_ber;
der_type_encoder_f ProfileInfoListError_encode_der;
xer_type_decoder_f ProfileInfoListError_decode_xer;
xer_type_encoder_f ProfileInfoListError_encode_xer;
oer_type_decoder_f ProfileInfoListError_decode_oer;
oer_type_encoder_f ProfileInfoListError_encode_oer;
per_type_decoder_f ProfileInfoListError_decode_uper;
per_type_encoder_f ProfileInfoListError_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ProfileInfoListError_H_ */
#include "asn_internal.h"
