/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ProfileState_H_
#define	_ProfileState_H_


#include "asn_application.h"

/* Including external dependencies */
#include "INTEGER.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProfileState {
	ProfileState_disabled	= 0,
	ProfileState_enabled	= 1
} e_ProfileState;

/* ProfileState */
typedef INTEGER_t	 ProfileState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProfileState;
asn_struct_free_f ProfileState_free;
asn_struct_print_f ProfileState_print;
asn_constr_check_f ProfileState_constraint;
ber_type_decoder_f ProfileState_decode_ber;
der_type_encoder_f ProfileState_encode_der;
xer_type_decoder_f ProfileState_decode_xer;
xer_type_encoder_f ProfileState_encode_xer;
oer_type_decoder_f ProfileState_decode_oer;
oer_type_encoder_f ProfileState_encode_oer;
per_type_decoder_f ProfileState_decode_uper;
per_type_encoder_f ProfileState_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ProfileState_H_ */
#include "asn_internal.h"
