/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ProfileInfoListRequest_H_
#define	_ProfileInfoListRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"
#include "OctetTo16.h"
#include "Iccid.h"
#include "ProfileClass.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProfileInfoListRequest__searchCriteria_PR {
	ProfileInfoListRequest__searchCriteria_PR_NOTHING,	/* No components present */
	ProfileInfoListRequest__searchCriteria_PR_isdpAid,
	ProfileInfoListRequest__searchCriteria_PR_iccid,
	ProfileInfoListRequest__searchCriteria_PR_profileClass
	/* Extensions may appear below */
	
} ProfileInfoListRequest__searchCriteria_PR;

/* ProfileInfoListRequest */
typedef struct ProfileInfoListRequest {
	struct ProfileInfoListRequest__searchCriteria {
		ProfileInfoListRequest__searchCriteria_PR present;
		union ProfileInfoListRequest__searchCriteria_u {
			OctetTo16_t	 isdpAid;
			Iccid_t	 iccid;
			ProfileClass_t	 profileClass;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *searchCriteria;
	OCTET_STRING_t	*tagList	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProfileInfoListRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProfileInfoListRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _ProfileInfoListRequest_H_ */
#include "asn_internal.h"
