/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ProfileInstallationResult_H_
#define	_ProfileInstallationResult_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ProfileInstallationResultData.h"
#include "EuiccSignPIR.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ProfileInstallationResult */
typedef struct ProfileInstallationResult {
	ProfileInstallationResultData_t	 profileInstallationResultData;
	EuiccSignPIR_t	 euiccSignPIR;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProfileInstallationResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProfileInstallationResult;
extern asn_SEQUENCE_specifics_t asn_SPC_ProfileInstallationResult_specs_1;
extern asn_TYPE_member_t asn_MBR_ProfileInstallationResult_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ProfileInstallationResult_H_ */
#include "asn_internal.h"
