/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ProfileInstallationResultData_H_
#define	_ProfileInstallationResultData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TransactionId.h"
#include "NotificationMetadata.h"
#include "OBJECT_IDENTIFIER.h"
#include "SuccessResult.h"
#include "ErrorResult.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProfileInstallationResultData__finalResult_PR {
	ProfileInstallationResultData__finalResult_PR_NOTHING,	/* No components present */
	ProfileInstallationResultData__finalResult_PR_successResult,
	ProfileInstallationResultData__finalResult_PR_errorResult
	/* Extensions may appear below */
	
} ProfileInstallationResultData__finalResult_PR;

/* ProfileInstallationResultData */
typedef struct ProfileInstallationResultData {
	TransactionId_t	 transactionId;
	NotificationMetadata_t	 notificationMetadata;
	OBJECT_IDENTIFIER_t	*smdpOid	/* OPTIONAL */;
	struct ProfileInstallationResultData__finalResult {
		ProfileInstallationResultData__finalResult_PR present;
		union ProfileInstallationResultData__finalResult_u {
			SuccessResult_t	 successResult;
			ErrorResult_t	 errorResult;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} finalResult;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProfileInstallationResultData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProfileInstallationResultData;
extern asn_SEQUENCE_specifics_t asn_SPC_ProfileInstallationResultData_specs_1;
extern asn_TYPE_member_t asn_MBR_ProfileInstallationResultData_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _ProfileInstallationResultData_H_ */
#include "asn_internal.h"
