/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "RefArDo.h"

static int
memb_deviceAppIdRefDo_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if(((size == 20) || (size == 32))) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_pkgRefDo_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size <= 127)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_permArDo_constraint_6(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_deviceAppIdRefDo_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(20..32)) */};
static asn_per_constraints_t asn_PER_memb_deviceAppIdRefDo_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  20,  32 }	/* (SIZE(20..32)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_pkgRefDo_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..127)) */};
static asn_per_constraints_t asn_PER_memb_pkgRefDo_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 7,  7,  0,  127 }	/* (SIZE(0..127)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_permArDo_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	8	/* (SIZE(8..8)) */};
static asn_per_constraints_t asn_PER_memb_permArDo_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  8,  8 }	/* (SIZE(8..8)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_refDo_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RefArDo__refDo, deviceAppIdRefDo),
		(ASN_TAG_CLASS_PRIVATE | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_deviceAppIdRefDo_constr_3, &asn_PER_memb_deviceAppIdRefDo_constr_3,  memb_deviceAppIdRefDo_constraint_2 },
		0, 0, /* No default value */
		"deviceAppIdRefDo"
		},
	{ ATF_POINTER, 1, offsetof(struct RefArDo__refDo, pkgRefDo),
		(ASN_TAG_CLASS_PRIVATE | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_pkgRefDo_constr_4, &asn_PER_memb_pkgRefDo_constr_4,  memb_pkgRefDo_constraint_2 },
		0, 0, /* No default value */
		"pkgRefDo"
		},
};
static const int asn_MAP_refDo_oms_2[] = { 1 };
static const ber_tlv_tag_t asn_DEF_refDo_tags_2[] = {
	(ASN_TAG_CLASS_PRIVATE | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_refDo_tag2el_2[] = {
    { (ASN_TAG_CLASS_PRIVATE | (1 << 2)), 0, 0, 0 }, /* deviceAppIdRefDo */
    { (ASN_TAG_CLASS_PRIVATE | (10 << 2)), 1, 0, 0 } /* pkgRefDo */
};
static asn_SEQUENCE_specifics_t asn_SPC_refDo_specs_2 = {
	sizeof(struct RefArDo__refDo),
	offsetof(struct RefArDo__refDo, _asn_ctx),
	asn_MAP_refDo_tag2el_2,
	2,	/* Count of tags in the map */
	asn_MAP_refDo_oms_2,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_refDo_2 = {
	"refDo",
	"refDo",
	&asn_OP_SEQUENCE,
	asn_DEF_refDo_tags_2,
	sizeof(asn_DEF_refDo_tags_2)
		/sizeof(asn_DEF_refDo_tags_2[0]) - 1, /* 1 */
	asn_DEF_refDo_tags_2,	/* Same as above */
	sizeof(asn_DEF_refDo_tags_2)
		/sizeof(asn_DEF_refDo_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_refDo_2,
	2,	/* Elements count */
	&asn_SPC_refDo_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_arDo_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RefArDo__arDo, permArDo),
		(ASN_TAG_CLASS_PRIVATE | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_permArDo_constr_7, &asn_PER_memb_permArDo_constr_7,  memb_permArDo_constraint_6 },
		0, 0, /* No default value */
		"permArDo"
		},
};
static const ber_tlv_tag_t asn_DEF_arDo_tags_6[] = {
	(ASN_TAG_CLASS_PRIVATE | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_arDo_tag2el_6[] = {
    { (ASN_TAG_CLASS_PRIVATE | (27 << 2)), 0, 0, 0 } /* permArDo */
};
static asn_SEQUENCE_specifics_t asn_SPC_arDo_specs_6 = {
	sizeof(struct RefArDo__arDo),
	offsetof(struct RefArDo__arDo, _asn_ctx),
	asn_MAP_arDo_tag2el_6,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_arDo_6 = {
	"arDo",
	"arDo",
	&asn_OP_SEQUENCE,
	asn_DEF_arDo_tags_6,
	sizeof(asn_DEF_arDo_tags_6)
		/sizeof(asn_DEF_arDo_tags_6[0]) - 1, /* 1 */
	asn_DEF_arDo_tags_6,	/* Same as above */
	sizeof(asn_DEF_arDo_tags_6)
		/sizeof(asn_DEF_arDo_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_arDo_6,
	1,	/* Elements count */
	&asn_SPC_arDo_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RefArDo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RefArDo, refDo),
		(ASN_TAG_CLASS_PRIVATE | (1 << 2)),
		0,
		&asn_DEF_refDo_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"refDo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RefArDo, arDo),
		(ASN_TAG_CLASS_PRIVATE | (3 << 2)),
		0,
		&asn_DEF_arDo_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"arDo"
		},
};
static const ber_tlv_tag_t asn_DEF_RefArDo_tags_1[] = {
	(ASN_TAG_CLASS_PRIVATE | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RefArDo_tag2el_1[] = {
    { (ASN_TAG_CLASS_PRIVATE | (1 << 2)), 0, 0, 0 }, /* refDo */
    { (ASN_TAG_CLASS_PRIVATE | (3 << 2)), 1, 0, 0 } /* arDo */
};
asn_SEQUENCE_specifics_t asn_SPC_RefArDo_specs_1 = {
	sizeof(struct RefArDo),
	offsetof(struct RefArDo, _asn_ctx),
	asn_MAP_RefArDo_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RefArDo = {
	"RefArDo",
	"RefArDo",
	&asn_OP_SEQUENCE,
	asn_DEF_RefArDo_tags_1,
	sizeof(asn_DEF_RefArDo_tags_1)
		/sizeof(asn_DEF_RefArDo_tags_1[0]) - 1, /* 1 */
	asn_DEF_RefArDo_tags_1,	/* Same as above */
	sizeof(asn_DEF_RefArDo_tags_1)
		/sizeof(asn_DEF_RefArDo_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RefArDo_1,
	2,	/* Elements count */
	&asn_SPC_RefArDo_specs_1	/* Additional specs */
};

