/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RemoteProfileProvisioningResponse_H_
#define	_RemoteProfileProvisioningResponse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "InitiateAuthenticationResponse.h"
#include "AuthenticateClientResponseEs9.h"
#include "GetBoundProfilePackageResponse.h"
#include "CancelSessionResponseEs9.h"
#include "AuthenticateClientResponseEs11.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RemoteProfileProvisioningResponse_PR {
	RemoteProfileProvisioningResponse_PR_NOTHING,	/* No components present */
	RemoteProfileProvisioningResponse_PR_initiateAuthenticationResponse,
	RemoteProfileProvisioningResponse_PR_authenticateClientResponseEs9,
	RemoteProfileProvisioningResponse_PR_getBoundProfilePackageResponse,
	RemoteProfileProvisioningResponse_PR_cancelSessionResponseEs9,
	RemoteProfileProvisioningResponse_PR_authenticateClientResponseEs11
	/* Extensions may appear below */
	
} RemoteProfileProvisioningResponse_PR;

/* RemoteProfileProvisioningResponse */
typedef struct RemoteProfileProvisioningResponse {
	RemoteProfileProvisioningResponse_PR present;
	union RemoteProfileProvisioningResponse_u {
		InitiateAuthenticationResponse_t	 initiateAuthenticationResponse;
		AuthenticateClientResponseEs9_t	 authenticateClientResponseEs9;
		GetBoundProfilePackageResponse_t	 getBoundProfilePackageResponse;
		CancelSessionResponseEs9_t	 cancelSessionResponseEs9;
		AuthenticateClientResponseEs11_t	 authenticateClientResponseEs11;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RemoteProfileProvisioningResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RemoteProfileProvisioningResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _RemoteProfileProvisioningResponse_H_ */
#include "asn_internal.h"
