/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "RemoteProfileProvisioningRequest.h"

static asn_oer_constraints_t asn_OER_type_RemoteProfileProvisioningRequest_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_RemoteProfileProvisioningRequest_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }	/* (0..4,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_RemoteProfileProvisioningRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RemoteProfileProvisioningRequest, choice.initiateAuthenticationRequest),
		(ASN_TAG_CLASS_CONTEXT | (57 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitiateAuthenticationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initiateAuthenticationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RemoteProfileProvisioningRequest, choice.authenticateClientRequest),
		(ASN_TAG_CLASS_CONTEXT | (59 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AuthenticateClientRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"authenticateClientRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RemoteProfileProvisioningRequest, choice.getBoundProfilePackageRequest),
		(ASN_TAG_CLASS_CONTEXT | (58 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GetBoundProfilePackageRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"getBoundProfilePackageRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RemoteProfileProvisioningRequest, choice.cancelSessionRequestEs9),
		(ASN_TAG_CLASS_CONTEXT | (65 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CancelSessionRequestEs9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cancelSessionRequestEs9"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RemoteProfileProvisioningRequest, choice.handleNotification),
		(ASN_TAG_CLASS_CONTEXT | (61 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandleNotification,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handleNotification"
		},
};
static const unsigned asn_MAP_RemoteProfileProvisioningRequest_to_canonical_1[] = { 0, 2, 1, 4, 3 };
static const unsigned asn_MAP_RemoteProfileProvisioningRequest_from_canonical_1[] = { 0, 2, 1, 4, 3 };
static const ber_tlv_tag_t asn_DEF_RemoteProfileProvisioningRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RemoteProfileProvisioningRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (57 << 2)), 0, 0, 0 }, /* initiateAuthenticationRequest */
    { (ASN_TAG_CLASS_CONTEXT | (58 << 2)), 2, 0, 0 }, /* getBoundProfilePackageRequest */
    { (ASN_TAG_CLASS_CONTEXT | (59 << 2)), 1, 0, 0 }, /* authenticateClientRequest */
    { (ASN_TAG_CLASS_CONTEXT | (61 << 2)), 4, 0, 0 }, /* handleNotification */
    { (ASN_TAG_CLASS_CONTEXT | (65 << 2)), 3, 0, 0 } /* cancelSessionRequestEs9 */
};
static asn_CHOICE_specifics_t asn_SPC_RemoteProfileProvisioningRequest_specs_1 = {
	sizeof(struct RemoteProfileProvisioningRequest),
	offsetof(struct RemoteProfileProvisioningRequest, _asn_ctx),
	offsetof(struct RemoteProfileProvisioningRequest, present),
	sizeof(((struct RemoteProfileProvisioningRequest *)0)->present),
	asn_MAP_RemoteProfileProvisioningRequest_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_RemoteProfileProvisioningRequest_to_canonical_1,
	asn_MAP_RemoteProfileProvisioningRequest_from_canonical_1,
	5	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_RemoteProfileProvisioningRequest = {
	"RemoteProfileProvisioningRequest",
	"RemoteProfileProvisioningRequest",
	&asn_OP_CHOICE,
	asn_DEF_RemoteProfileProvisioningRequest_tags_1,
	sizeof(asn_DEF_RemoteProfileProvisioningRequest_tags_1)
		/sizeof(asn_DEF_RemoteProfileProvisioningRequest_tags_1[0]), /* 1 */
	asn_DEF_RemoteProfileProvisioningRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_RemoteProfileProvisioningRequest_tags_1)
		/sizeof(asn_DEF_RemoteProfileProvisioningRequest_tags_1[0]), /* 1 */
	{ &asn_OER_type_RemoteProfileProvisioningRequest_constr_1, &asn_PER_type_RemoteProfileProvisioningRequest_constr_1, CHOICE_constraint },
	asn_MBR_RemoteProfileProvisioningRequest_1,
	5,	/* Elements count */
	&asn_SPC_RemoteProfileProvisioningRequest_specs_1	/* Additional specs */
};

