/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RetrieveNotificationsListResponse_H_
#define	_RetrieveNotificationsListResponse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "INTEGER.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RetrieveNotificationsListResponse_PR {
	RetrieveNotificationsListResponse_PR_NOTHING,	/* No components present */
	RetrieveNotificationsListResponse_PR_notificationList,
	RetrieveNotificationsListResponse_PR_notificationsListResultError
	/* Extensions may appear below */
	
} RetrieveNotificationsListResponse_PR;
typedef enum RetrieveNotificationsListResponse__notificationsListResultError {
	RetrieveNotificationsListResponse__notificationsListResultError_noResultAvailable	= 1,
	RetrieveNotificationsListResponse__notificationsListResultError_undefinedError	= 127
} e_RetrieveNotificationsListResponse__notificationsListResultError;

/* Forward declarations */
struct PendingNotification;

/* RetrieveNotificationsListResponse */
typedef struct RetrieveNotificationsListResponse {
	RetrieveNotificationsListResponse_PR present;
	union RetrieveNotificationsListResponse_u {
		struct RetrieveNotificationsListResponse__notificationList {
			A_SEQUENCE_OF(struct PendingNotification) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} notificationList;
		INTEGER_t	 notificationsListResultError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RetrieveNotificationsListResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RetrieveNotificationsListResponse;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PendingNotification.h"

#endif	/* _RetrieveNotificationsListResponse_H_ */
#include "asn_internal.h"
