/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RetrieveNotificationsListRequest_H_
#define	_RetrieveNotificationsListRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "INTEGER.h"
#include "NotificationEvent.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RetrieveNotificationsListRequest__searchCriteria_PR {
	RetrieveNotificationsListRequest__searchCriteria_PR_NOTHING,	/* No components present */
	RetrieveNotificationsListRequest__searchCriteria_PR_seqNumber,
	RetrieveNotificationsListRequest__searchCriteria_PR_profileManagementOperation
	/* Extensions may appear below */
	
} RetrieveNotificationsListRequest__searchCriteria_PR;

/* RetrieveNotificationsListRequest */
typedef struct RetrieveNotificationsListRequest {
	struct RetrieveNotificationsListRequest__searchCriteria {
		RetrieveNotificationsListRequest__searchCriteria_PR present;
		union RetrieveNotificationsListRequest__searchCriteria_u {
			INTEGER_t	 seqNumber;
			NotificationEvent_t	 profileManagementOperation;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *searchCriteria;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RetrieveNotificationsListRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RetrieveNotificationsListRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _RetrieveNotificationsListRequest_H_ */
#include "asn_internal.h"
