/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "SeqSecondBoundProfilePackageTLV87.h"

asn_TYPE_member_t asn_MBR_SeqSecondBoundProfilePackageTLV87_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		0,
		&asn_DEF_BoundProfilePackageTLV87,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_SeqSecondBoundProfilePackageTLV87_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_SeqSecondBoundProfilePackageTLV87_specs_1 = {
	sizeof(struct SeqSecondBoundProfilePackageTLV87),
	offsetof(struct SeqSecondBoundProfilePackageTLV87, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_SeqSecondBoundProfilePackageTLV87 = {
	"SeqSecondBoundProfilePackageTLV87",
	"SeqSecondBoundProfilePackageTLV87",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_SeqSecondBoundProfilePackageTLV87_tags_1,
	sizeof(asn_DEF_SeqSecondBoundProfilePackageTLV87_tags_1)
		/sizeof(asn_DEF_SeqSecondBoundProfilePackageTLV87_tags_1[0]) - 1, /* 1 */
	asn_DEF_SeqSecondBoundProfilePackageTLV87_tags_1,	/* Same as above */
	sizeof(asn_DEF_SeqSecondBoundProfilePackageTLV87_tags_1)
		/sizeof(asn_DEF_SeqSecondBoundProfilePackageTLV87_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_SeqSecondBoundProfilePackageTLV87_1,
	1,	/* Single element */
	&asn_SPC_SeqSecondBoundProfilePackageTLV87_specs_1	/* Additional specs */
};

