/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ServerSigned1_H_
#define	_ServerSigned1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TransactionId.h"
#include "Octet16.h"
#include "UTF8String.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ServerSigned1 */
typedef struct ServerSigned1 {
	TransactionId_t	 transactionId;
	Octet16_t	 euiccChallenge;
	UTF8String_t	 serverAddress;
	Octet16_t	 serverChallenge;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServerSigned1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServerSigned1;
extern asn_SEQUENCE_specifics_t asn_SPC_ServerSigned1_specs_1;
extern asn_TYPE_member_t asn_MBR_ServerSigned1_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _ServerSigned1_H_ */
#include "asn_internal.h"
