/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SetDefaultDpAddressRequest_H_
#define	_SetDefaultDpAddressRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "UTF8String.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SetDefaultDpAddressRequest */
typedef struct SetDefaultDpAddressRequest {
	UTF8String_t	 defaultDpAddress;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetDefaultDpAddressRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetDefaultDpAddressRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _SetDefaultDpAddressRequest_H_ */
#include "asn_internal.h"
