/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SetDefaultDpAddressResponse_H_
#define	_SetDefaultDpAddressResponse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "INTEGER.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SetDefaultDpAddressResponse__setDefaultDpAddressResult {
	SetDefaultDpAddressResponse__setDefaultDpAddressResult_ok	= 0,
	SetDefaultDpAddressResponse__setDefaultDpAddressResult_undefinedError	= 127
} e_SetDefaultDpAddressResponse__setDefaultDpAddressResult;

/* SetDefaultDpAddressResponse */
typedef struct SetDefaultDpAddressResponse {
	INTEGER_t	 setDefaultDpAddressResult;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetDefaultDpAddressResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetDefaultDpAddressResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _SetDefaultDpAddressResponse_H_ */
#include "asn_internal.h"
