/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SetNicknameRequest_H_
#define	_SetNicknameRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Iccid.h"
#include "UTF8String.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SetNicknameRequest */
typedef struct SetNicknameRequest {
	Iccid_t	 iccid;
	UTF8String_t	 profileNickname;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetNicknameRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetNicknameRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _SetNicknameRequest_H_ */
#include "asn_internal.h"
