/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "SmdpSigned2.h"

asn_TYPE_member_t asn_MBR_SmdpSigned2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SmdpSigned2, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SmdpSigned2, ccRequiredFlag),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ccRequiredFlag"
		},
	{ ATF_POINTER, 1, offsetof(struct SmdpSigned2, bppEuiccOtpk),
		(ASN_TAG_CLASS_APPLICATION | (73 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bppEuiccOtpk"
		},
};
static const int asn_MAP_SmdpSigned2_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_SmdpSigned2_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SmdpSigned2_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 1, 0, 0 }, /* ccRequiredFlag */
    { (ASN_TAG_CLASS_APPLICATION | (73 << 2)), 2, 0, 0 }, /* bppEuiccOtpk */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* transactionId */
};
asn_SEQUENCE_specifics_t asn_SPC_SmdpSigned2_specs_1 = {
	sizeof(struct SmdpSigned2),
	offsetof(struct SmdpSigned2, _asn_ctx),
	asn_MAP_SmdpSigned2_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_SmdpSigned2_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SmdpSigned2 = {
	"SmdpSigned2",
	"SmdpSigned2",
	&asn_OP_SEQUENCE,
	asn_DEF_SmdpSigned2_tags_1,
	sizeof(asn_DEF_SmdpSigned2_tags_1)
		/sizeof(asn_DEF_SmdpSigned2_tags_1[0]), /* 1 */
	asn_DEF_SmdpSigned2_tags_1,	/* Same as above */
	sizeof(asn_DEF_SmdpSigned2_tags_1)
		/sizeof(asn_DEF_SmdpSigned2_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SmdpSigned2_1,
	3,	/* Elements count */
	&asn_SPC_SmdpSigned2_specs_1	/* Additional specs */
};

