/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_StoreMetadataRequest_H_
#define	_StoreMetadataRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Iccid.h"
#include "UTF8String.h"
#include "IconType.h"
#include "OCTET_STRING.h"
#include "ProfileClass.h"
#include "PprIds.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OperatorID;
struct NotificationConfigurationInformation;

/* StoreMetadataRequest */
typedef struct StoreMetadataRequest {
	Iccid_t	 iccid;
	UTF8String_t	 serviceProviderName;
	UTF8String_t	 profileName;
	IconType_t	*iconType	/* OPTIONAL */;
	OCTET_STRING_t	*icon	/* OPTIONAL */;
	ProfileClass_t	*profileClass	/* OPTIONAL */;
	struct StoreMetadataRequest__notificationConfigurationInfo {
		A_SEQUENCE_OF(struct NotificationConfigurationInformation) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *notificationConfigurationInfo;
	struct OperatorID	*profileOwner	/* OPTIONAL */;
	PprIds_t	*profilePolicyRules	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StoreMetadataRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StoreMetadataRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_StoreMetadataRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_StoreMetadataRequest_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OperatorID.h"
#include "NotificationConfigurationInformation.h"

#endif	/* _StoreMetadataRequest_H_ */
#include "asn_internal.h"
