/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "StoreMetadataRequest.h"

static int
memb_serviceProviderName_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_profileName_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 64)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_icon_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size <= 1024)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_serviceProviderName_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_serviceProviderName_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_profileName_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_profileName_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_icon_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..1024)) */};
static asn_per_constraints_t asn_PER_memb_icon_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 11,  11,  0,  1024 }	/* (SIZE(0..1024)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_notificationConfigurationInfo_8[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NotificationConfigurationInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_notificationConfigurationInfo_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_notificationConfigurationInfo_specs_8 = {
	sizeof(struct StoreMetadataRequest__notificationConfigurationInfo),
	offsetof(struct StoreMetadataRequest__notificationConfigurationInfo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_notificationConfigurationInfo_8 = {
	"notificationConfigurationInfo",
	"notificationConfigurationInfo",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_notificationConfigurationInfo_tags_8,
	sizeof(asn_DEF_notificationConfigurationInfo_tags_8)
		/sizeof(asn_DEF_notificationConfigurationInfo_tags_8[0]) - 1, /* 1 */
	asn_DEF_notificationConfigurationInfo_tags_8,	/* Same as above */
	sizeof(asn_DEF_notificationConfigurationInfo_tags_8)
		/sizeof(asn_DEF_notificationConfigurationInfo_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_notificationConfigurationInfo_8,
	1,	/* Single element */
	&asn_SPC_notificationConfigurationInfo_specs_8	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_StoreMetadataRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct StoreMetadataRequest, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		0,
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StoreMetadataRequest, serviceProviderName),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_serviceProviderName_constr_3, &asn_PER_memb_serviceProviderName_constr_3,  memb_serviceProviderName_constraint_1 },
		0, 0, /* No default value */
		"serviceProviderName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StoreMetadataRequest, profileName),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_profileName_constr_4, &asn_PER_memb_profileName_constr_4,  memb_profileName_constraint_1 },
		0, 0, /* No default value */
		"profileName"
		},
	{ ATF_POINTER, 6, offsetof(struct StoreMetadataRequest, iconType),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IconType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iconType"
		},
	{ ATF_POINTER, 5, offsetof(struct StoreMetadataRequest, icon),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_icon_constr_6, &asn_PER_memb_icon_constr_6,  memb_icon_constraint_1 },
		0, 0, /* No default value */
		"icon"
		},
	{ ATF_POINTER, 4, offsetof(struct StoreMetadataRequest, profileClass),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProfileClass,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileClass"
		},
	{ ATF_POINTER, 3, offsetof(struct StoreMetadataRequest, notificationConfigurationInfo),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		0,
		&asn_DEF_notificationConfigurationInfo_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notificationConfigurationInfo"
		},
	{ ATF_POINTER, 2, offsetof(struct StoreMetadataRequest, profileOwner),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OperatorID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileOwner"
		},
	{ ATF_POINTER, 1, offsetof(struct StoreMetadataRequest, profilePolicyRules),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PprIds,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profilePolicyRules"
		},
};
static const int asn_MAP_StoreMetadataRequest_oms_1[] = { 3, 4, 5, 6, 7, 8 };
static const ber_tlv_tag_t asn_DEF_StoreMetadataRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (37 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_StoreMetadataRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 }, /* iccid */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 1, 0, 0 }, /* serviceProviderName */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 2, 0, 0 }, /* profileName */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 3, 0, 0 }, /* iconType */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 4, 0, 0 }, /* icon */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 5, 0, 0 }, /* profileClass */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 6, 0, 0 }, /* notificationConfigurationInfo */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 7, 0, 0 }, /* profileOwner */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 8, 0, 0 } /* profilePolicyRules */
};
asn_SEQUENCE_specifics_t asn_SPC_StoreMetadataRequest_specs_1 = {
	sizeof(struct StoreMetadataRequest),
	offsetof(struct StoreMetadataRequest, _asn_ctx),
	asn_MAP_StoreMetadataRequest_tag2el_1,
	9,	/* Count of tags in the map */
	asn_MAP_StoreMetadataRequest_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	9,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_StoreMetadataRequest = {
	"StoreMetadataRequest",
	"StoreMetadataRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_StoreMetadataRequest_tags_1,
	sizeof(asn_DEF_StoreMetadataRequest_tags_1)
		/sizeof(asn_DEF_StoreMetadataRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_StoreMetadataRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_StoreMetadataRequest_tags_1)
		/sizeof(asn_DEF_StoreMetadataRequest_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_StoreMetadataRequest_1,
	9,	/* Elements count */
	&asn_SPC_StoreMetadataRequest_specs_1	/* Additional specs */
};

