/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "UpdateMetadataRequest.h"

static int
memb_serviceProviderName_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_profileName_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 64)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_icon_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size <= 1024)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_serviceProviderName_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_serviceProviderName_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_profileName_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_profileName_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_icon_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..1024)) */};
static asn_per_constraints_t asn_PER_memb_icon_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 11,  11,  0,  1024 }	/* (SIZE(0..1024)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_UpdateMetadataRequest_1[] = {
	{ ATF_POINTER, 5, offsetof(struct UpdateMetadataRequest, serviceProviderName),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_serviceProviderName_constr_2, &asn_PER_memb_serviceProviderName_constr_2,  memb_serviceProviderName_constraint_1 },
		0, 0, /* No default value */
		"serviceProviderName"
		},
	{ ATF_POINTER, 4, offsetof(struct UpdateMetadataRequest, profileName),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_profileName_constr_3, &asn_PER_memb_profileName_constr_3,  memb_profileName_constraint_1 },
		0, 0, /* No default value */
		"profileName"
		},
	{ ATF_POINTER, 3, offsetof(struct UpdateMetadataRequest, iconType),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IconType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iconType"
		},
	{ ATF_POINTER, 2, offsetof(struct UpdateMetadataRequest, icon),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_icon_constr_5, &asn_PER_memb_icon_constr_5,  memb_icon_constraint_1 },
		0, 0, /* No default value */
		"icon"
		},
	{ ATF_POINTER, 1, offsetof(struct UpdateMetadataRequest, profilePolicyRules),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PprIds,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profilePolicyRules"
		},
};
static const int asn_MAP_UpdateMetadataRequest_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_UpdateMetadataRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (42 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UpdateMetadataRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 0, 0, 0 }, /* serviceProviderName */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 1, 0, 0 }, /* profileName */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 2, 0, 0 }, /* iconType */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 3, 0, 0 }, /* icon */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 4, 0, 0 } /* profilePolicyRules */
};
static asn_SEQUENCE_specifics_t asn_SPC_UpdateMetadataRequest_specs_1 = {
	sizeof(struct UpdateMetadataRequest),
	offsetof(struct UpdateMetadataRequest, _asn_ctx),
	asn_MAP_UpdateMetadataRequest_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_UpdateMetadataRequest_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UpdateMetadataRequest = {
	"UpdateMetadataRequest",
	"UpdateMetadataRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_UpdateMetadataRequest_tags_1,
	sizeof(asn_DEF_UpdateMetadataRequest_tags_1)
		/sizeof(asn_DEF_UpdateMetadataRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_UpdateMetadataRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_UpdateMetadataRequest_tags_1)
		/sizeof(asn_DEF_UpdateMetadataRequest_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UpdateMetadataRequest_1,
	5,	/* Elements count */
	&asn_SPC_UpdateMetadataRequest_specs_1	/* Additional specs */
};

