/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_UpdateMetadataRequest_H_
#define	_UpdateMetadataRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "UTF8String.h"
#include "IconType.h"
#include "OCTET_STRING.h"
#include "PprIds.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UpdateMetadataRequest */
typedef struct UpdateMetadataRequest {
	UTF8String_t	*serviceProviderName	/* OPTIONAL */;
	UTF8String_t	*profileName	/* OPTIONAL */;
	IconType_t	*iconType	/* OPTIONAL */;
	OCTET_STRING_t	*icon	/* OPTIONAL */;
	PprIds_t	*profilePolicyRules	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UpdateMetadataRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UpdateMetadataRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _UpdateMetadataRequest_H_ */
#include "asn_internal.h"
