/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/rsp.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_VersionType_H_
#define	_VersionType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VersionType */
typedef OCTET_STRING_t	 VersionType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VersionType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VersionType;
asn_struct_free_f VersionType_free;
asn_struct_print_f VersionType_print;
asn_constr_check_f VersionType_constraint;
ber_type_decoder_f VersionType_decode_ber;
der_type_encoder_f VersionType_encode_der;
xer_type_decoder_f VersionType_decode_xer;
xer_type_encoder_f VersionType_encode_xer;
oer_type_decoder_f VersionType_decode_oer;
oer_type_encoder_f VersionType_encode_oer;
per_type_decoder_f VersionType_decode_uper;
per_type_encoder_f VersionType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VersionType_H_ */
#include "asn_internal.h"
